using System.IO;
using System.Text;
using Es;
using UnityEditor;
using UnityEngine;

namespace editor.UITools
{
    public class UIEnumGenerator : AssetPostprocessor
    {
        public static string OUPUT_PANEL_ID_ENUM_PATH => Application.dataPath + "/Scripts/GameData/UIConfig/PanelId.cs"; 
        public static string OUPUT_WINDOW_ID_ENUM_PATH => Application.dataPath + "/Scripts/GameData/UIConfig/WindowId.cs";

        public const string UI_PANEL_CONFIG_PATH = "Assets/Arts/Config/Asset/UIPanel.asset";
        public const string UI_WINDOW_CONFIG_PATH = "Assets/Arts/Config/Asset/UIWindow.asset";

        // 导入后自动生成枚举脚本
        private static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            bool isReGen = false;
            foreach (string str in importedAssets)
            {
                // Debug.Log("Reimported Asset: " + str);
                if (str.Contains("UIPanel.asset") || str.Contains("UIWindow.asset"))
                {
                    isReGen = true;
                    break;
                }
            }

            if (isReGen)
            {
                GenerateAll();
            }
        }

        public static void GenerateAll()
        {
            Debug.Log("开始自动生成Panel/Window枚举");
            GeneratePanelEnumFile();
            GenerateWindowEnumFile();
            Debug.Log("自动生成Panel/Window枚举脚本结束！");
            // EditorUtility.DisplayDialog(nameof(UIEnumGenerator), "生成UI枚举成功", "6");
        }

        private static void GeneratePanelEnumFile()
        {
            var uiPanelTable = LoadConfig<UIPanelTable>(UI_PANEL_CONFIG_PATH);
            if (uiPanelTable == null)
            {
                Debug.LogError("uiPanelTable is null ,pls check!");
                return;
            }

            StringBuilder sb = new StringBuilder();
            GenAutoHeader(sb);
            sb.AppendLine("public enum PanelId");
            sb.AppendLine("{");

            foreach (var panelConfig in uiPanelTable.DataList)
            {
                if (string.IsNullOrEmpty(panelConfig.Name) == false)
                {
                    sb.AppendLine($"    {panelConfig.Name} = {panelConfig.PanelId},");
                }
            }

            sb.AppendLine("}");


            if (File.Exists(OUPUT_PANEL_ID_ENUM_PATH))
            {
                File.WriteAllText(OUPUT_PANEL_ID_ENUM_PATH, sb.ToString());
                Debug.Log("GeneratePanelEnumFile success");
            }
            else
            {
                Debug.LogError($"{OUPUT_PANEL_ID_ENUM_PATH} not exist!!");
            }
        }

        private static void GenerateWindowEnumFile()
        {
            var uiWindowTable = LoadConfig<UIWindowTable>(UI_WINDOW_CONFIG_PATH);
            if (uiWindowTable == null)
            {
                Debug.LogError("uiWindowTable is null ,pls check!");
                return;
            }

            StringBuilder sb = new StringBuilder();
            GenAutoHeader(sb);
            sb.AppendLine("public enum WindowId");
            sb.AppendLine("{");
            sb.AppendLine("    None = 0,");

            foreach (var w in uiWindowTable.DataList)
            {
                if (string.IsNullOrEmpty(w.Name) == false)
                {
                    sb.AppendLine($"    {w.Name} = {w.WindowId},");
                }
            }

            sb.AppendLine("}");

            if (File.Exists(OUPUT_WINDOW_ID_ENUM_PATH))
            {
                File.WriteAllText(OUPUT_WINDOW_ID_ENUM_PATH, sb.ToString());
                Debug.Log("GenerateWindowEnumFile success");
            }
            else
            {
                Debug.LogError($"{OUPUT_WINDOW_ID_ENUM_PATH} not exist!!");
            }
        }

        public static void GenAutoHeader(StringBuilder sb)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// This script is generated by tools");
            sb.AppendLine("/// 工具生成脚本，请勿手动编辑！！");
            sb.AppendLine("/// </summary>");
        }

        public static T LoadConfig<T>(string filePath) where T : ScriptableObject
        {
            var t = AssetDatabase.LoadAssetAtPath<T>(filePath);
            return t;
        }
    }
}