// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: store.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Network.Message {

  /// <summary>Holder for reflection information generated from store.proto</summary>
  public static partial class StoreReflection {

    #region Descriptor
    /// <summary>File descriptor for store.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StoreReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtzdG9yZS5wcm90bxIPTmV0d29yay5NZXNzYWdlIuEBChhHZXRQcm9kdWN0",
            "c0J5Q2F0ZWdvcnlSZXESCwoDdWlkGAEgASgJEg8KB3ZlcnNpb24YAiABKAkS",
            "DgoGY29va2llGAMgASgJEjEKC3Byb2R1Y3RUeXBlGAQgASgOMhwuTmV0d29y",
            "ay5NZXNzYWdlLlByb2R1Y3RUeXBlEjAKB3N1YlR5cGUYBSABKA4yHy5OZXR3",
            "b3JrLk1lc3NhZ2UuUHJvZHVjdFN1YlR5cGUSMgoGZmlsdGVyGAYgASgLMiIu",
            "TmV0d29yay5NZXNzYWdlLkdldFByb2R1Y3RzRmlsdGVyIv4BChhHZXRQcm9k",
            "dWN0c0J5Q2F0ZWdvcnlSc3ASDgoGY29va2llGAEgASgJEg0KBWlzRW5kGAIg",
            "ASgFEioKCHByb2R1Y3RzGAMgAygLMhguTmV0d29yay5NZXNzYWdlLlByb2R1",
            "Y3QSMQoLcHJvZHVjdFR5cGUYBCABKA4yHC5OZXR3b3JrLk1lc3NhZ2UuUHJv",
            "ZHVjdFR5cGUSMAoHc3ViVHlwZRgFIAEoDjIfLk5ldHdvcmsuTWVzc2FnZS5Q",
            "cm9kdWN0U3ViVHlwZRIyCgZmaWx0ZXIYBiABKAsyIi5OZXR3b3JrLk1lc3Nh",
            "Z2UuR2V0UHJvZHVjdHNGaWx0ZXIixwQKB1Byb2R1Y3QSCgoCaWQYASABKAkS",
            "FAoMY2xhc3NpZnlUeXBlGAIgASgFEg0KBXBnY0lkGAMgASgFEg4KBml0ZW1J",
            "ZBgEIAEoCRIPCgdiYXRjaElkGAUgASgJEioKBHR5cGUYBiABKA4yHC5OZXR3",
            "b3JrLk1lc3NhZ2UuUHJvZHVjdFR5cGUSDAoEbmFtZRgHIAEoCRIMCgRkZXNj",
            "GAggASgJEg0KBXByaWNlGAkgASgFEg4KBnN1cHBseRgKIAEoBRIPCgd2ZXJz",
            "aW9uGAsgASgFEjMKDHB1cmNoYXNlVHlwZRgMIAEoDjIdLk5ldHdvcmsuTWVz",
            "c2FnZS5QdXJjaGFzZVR5cGUSJQoFbGV2ZWwYDSABKA4yFi5OZXR3b3JrLk1l",
            "c3NhZ2UuTGV2ZWwSMAoHc3ViVHlwZRgOIAEoDjIfLk5ldHdvcmsuTWVzc2Fn",
            "ZS5Qcm9kdWN0U3ViVHlwZRIQCghvd25lZE51bRgPIAEoBRISCgpzb2xkU3Rh",
            "dHVzGBAgASgFEicKBnNvdXJjZRgRIAEoDjIXLk5ldHdvcmsuTWVzc2FnZS5T",
            "b3VyY2USOQoPZXh0cmFBdHRyaWJ1dGVzGBIgASgLMiAuTmV0d29yay5NZXNz",
            "YWdlLkV4dHJhQXR0cmlidXRlcxI1Cg1leHRyYUp1bXBEYXRhGBMgASgLMh4u",
            "TmV0d29yay5NZXNzYWdlLkV4dHJhSnVtcERhdGESEwoLY2FuQnlEaXJlY3QY",
            "FCABKAgSDgoGc3RhdHVzGBUgASgFIjMKD0V4dHJhQXR0cmlidXRlcxIOCgZz",
            "ZXROdW0YASABKAUSEAoIZGlzY291bnQYAiABKAUiLAoRR2V0UHJvZHVjdHNG",
            "aWx0ZXISFwoPb25seUNhbkJ5RGlyZWN0GAEgASgIImEKDUV4dHJhSnVtcERh",
            "dGESFAoMZG93bnRvd25UYWdzGAEgAygJEhIKCnJvdGFyeVRhZ3MYAiADKAkS",
            "FAoMYmxpbmRCb3hUYWdzGAMgAygJEhAKCHRhc2tUYWdzGAQgAygJKoQBCgtQ",
            "cm9kdWN0VHlwZRILCgdVbmtub3duEAASCwoHQ2xvdGhlcxABEgkKBUVtb3Rl",
            "EAISDAoIUGFzc0NhcmQQAxIICgRJdGVtEAQSCgoGUG90aW9uEAUSCgoGT3V0",
            "Zml0EAYSDQoJVmFsdWVQYWNrEAcSEQoNSW50aW1hY3lQcm9wcxAIKmgKDFB1",
            "cmNoYXNlVHlwZRIWChJVbmtvd25QdXJjaGFzZVR5cGUQABITCg9QdXJjaGFz",
            "ZVR5cGVHZW0QARIUChBQdXJjaGFzZVR5cGVDb2luEAISFQoRUHVyY2hhc2VU",
            "eXBlQnVkZ2UQAyqgAQoGU291cmNlEhAKDFVua293blNvdXJjZRAAEg0KCUJ1",
            "eURpcmVjdBABEgsKB1ZlbmRpbmcQAhIJCgVUd2lzdBADEgoKBlJvdGFyeRAE",
            "EgwKCEJsaW5kQm94EAUSDwoLU3RhcnRlclBhY2sQBhIPCgtNb250aGx5Q2Fy",
            "ZBAHEhEKDVJlY2hhcmdlVG90YWwQCBIOCgpUYXNrUmV3YXJkEAkqNAoFTGV2",
            "ZWwSDwoLVW5rb3duTGV2ZWwQABIFCgFTEAESBQoBQRACEgUKAUIQAxIFCgFD",
            "EAQqsAEKDlByb2R1Y3RTdWJUeXBlEhkKFVVua25vd25Qcm9kdWN0U3ViVHlw",
            "ZRAAEg0KCEhhbmRoZWxkEOgHEgwKB1ZlaGljbGUQ6QcSFgoRTXVzaWNhbElu",
            "c3RydW1lbnQQ6gcSEAoLU3BlY2lhbEl0ZW0Q6wcSFgoRU2luZ2xlUGVyc29u",
            "RW1vdGUQ7AcSFwoSRG91YmxlUGVyc2lvbkVtb3RlEO0HEgsKBlNvY2lhbBDu",
            "B2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Network.Message.ProductType), typeof(global::Network.Message.PurchaseType), typeof(global::Network.Message.Source), typeof(global::Network.Message.Level), typeof(global::Network.Message.ProductSubType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Message.GetProductsByCategoryReq), global::Network.Message.GetProductsByCategoryReq.Parser, new[]{ "Uid", "Version", "Cookie", "ProductType", "SubType", "Filter" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Message.GetProductsByCategoryRsp), global::Network.Message.GetProductsByCategoryRsp.Parser, new[]{ "Cookie", "IsEnd", "Products", "ProductType", "SubType", "Filter" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Message.Product), global::Network.Message.Product.Parser, new[]{ "Id", "ClassifyType", "PgcId", "ItemId", "BatchId", "Type", "Name", "Desc", "Price", "Supply", "Version", "PurchaseType", "Level", "SubType", "OwnedNum", "SoldStatus", "Source", "ExtraAttributes", "ExtraJumpData", "CanByDirect", "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Message.ExtraAttributes), global::Network.Message.ExtraAttributes.Parser, new[]{ "SetNum", "Discount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Message.GetProductsFilter), global::Network.Message.GetProductsFilter.Parser, new[]{ "OnlyCanByDirect" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Message.ExtraJumpData), global::Network.Message.ExtraJumpData.Parser, new[]{ "DowntownTags", "RotaryTags", "BlindBoxTags", "TaskTags" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ProductType {
    [pbr::OriginalName("Unknown")] Unknown = 0,
    [pbr::OriginalName("Clothes")] Clothes = 1,
    [pbr::OriginalName("Emote")] Emote = 2,
    [pbr::OriginalName("PassCard")] PassCard = 3,
    [pbr::OriginalName("Item")] Item = 4,
    [pbr::OriginalName("Potion")] Potion = 5,
    [pbr::OriginalName("Outfit")] Outfit = 6,
    [pbr::OriginalName("ValuePack")] ValuePack = 7,
    [pbr::OriginalName("IntimacyProps")] IntimacyProps = 8,
  }

  public enum PurchaseType {
    [pbr::OriginalName("UnkownPurchaseType")] UnkownPurchaseType = 0,
    [pbr::OriginalName("PurchaseTypeGem")] Gem = 1,
    [pbr::OriginalName("PurchaseTypeCoin")] Coin = 2,
    [pbr::OriginalName("PurchaseTypeBudge")] Budge = 3,
  }

  public enum Source {
    [pbr::OriginalName("UnkownSource")] UnkownSource = 0,
    /// <summary>
    /// 直氪
    /// </summary>
    [pbr::OriginalName("BuyDirect")] BuyDirect = 1,
    /// <summary>
    /// 售卖机
    /// </summary>
    [pbr::OriginalName("Vending")] Vending = 2,
    /// <summary>
    /// 扭蛋机
    /// </summary>
    [pbr::OriginalName("Twist")] Twist = 3,
    /// <summary>
    /// 转盘
    /// </summary>
    [pbr::OriginalName("Rotary")] Rotary = 4,
    /// <summary>
    /// 盲盒
    /// </summary>
    [pbr::OriginalName("BlindBox")] BlindBox = 5,
    /// <summary>
    /// 新手礼包
    /// </summary>
    [pbr::OriginalName("StarterPack")] StarterPack = 6,
    [pbr::OriginalName("MonthlyCard")] MonthlyCard = 7,
    [pbr::OriginalName("RechargeTotal")] RechargeTotal = 8,
    [pbr::OriginalName("TaskReward")] TaskReward = 9,
  }

  public enum Level {
    [pbr::OriginalName("UnkownLevel")] UnkownLevel = 0,
    [pbr::OriginalName("S")] S = 1,
    [pbr::OriginalName("A")] A = 2,
    [pbr::OriginalName("B")] B = 3,
    [pbr::OriginalName("C")] C = 4,
  }

  public enum ProductSubType {
    [pbr::OriginalName("UnknownProductSubType")] UnknownProductSubType = 0,
    [pbr::OriginalName("Handheld")] Handheld = 1000,
    [pbr::OriginalName("Vehicle")] Vehicle = 1001,
    [pbr::OriginalName("MusicalInstrument")] MusicalInstrument = 1002,
    [pbr::OriginalName("SpecialItem")] SpecialItem = 1003,
    [pbr::OriginalName("SinglePersonEmote")] SinglePersonEmote = 1004,
    [pbr::OriginalName("DoublePersionEmote")] DoublePersionEmote = 1005,
    /// <summary>
    /// 亲密度道具
    /// </summary>
    [pbr::OriginalName("Social")] Social = 1006,
  }

  #endregion

  #region Messages
  public sealed partial class GetProductsByCategoryReq : pb::IMessage<GetProductsByCategoryReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetProductsByCategoryReq> _parser = new pb::MessageParser<GetProductsByCategoryReq>(() => new GetProductsByCategoryReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetProductsByCategoryReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Message.StoreReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetProductsByCategoryReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetProductsByCategoryReq(GetProductsByCategoryReq other) : this() {
      uid_ = other.uid_;
      version_ = other.version_;
      cookie_ = other.cookie_;
      productType_ = other.productType_;
      subType_ = other.subType_;
      filter_ = other.filter_ != null ? other.filter_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetProductsByCategoryReq Clone() {
      return new GetProductsByCategoryReq(this);
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private string uid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 2;
    private string version_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cookie" field.</summary>
    public const int CookieFieldNumber = 3;
    private string cookie_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cookie {
      get { return cookie_; }
      set {
        cookie_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "productType" field.</summary>
    public const int ProductTypeFieldNumber = 4;
    private global::Network.Message.ProductType productType_ = global::Network.Message.ProductType.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.ProductType ProductType {
      get { return productType_; }
      set {
        productType_ = value;
      }
    }

    /// <summary>Field number for the "subType" field.</summary>
    public const int SubTypeFieldNumber = 5;
    private global::Network.Message.ProductSubType subType_ = global::Network.Message.ProductSubType.UnknownProductSubType;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.ProductSubType SubType {
      get { return subType_; }
      set {
        subType_ = value;
      }
    }

    /// <summary>Field number for the "filter" field.</summary>
    public const int FilterFieldNumber = 6;
    private global::Network.Message.GetProductsFilter filter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.GetProductsFilter Filter {
      get { return filter_; }
      set {
        filter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetProductsByCategoryReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetProductsByCategoryReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      if (Version != other.Version) return false;
      if (Cookie != other.Cookie) return false;
      if (ProductType != other.ProductType) return false;
      if (SubType != other.SubType) return false;
      if (!object.Equals(Filter, other.Filter)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uid.Length != 0) hash ^= Uid.GetHashCode();
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      if (Cookie.Length != 0) hash ^= Cookie.GetHashCode();
      if (ProductType != global::Network.Message.ProductType.Unknown) hash ^= ProductType.GetHashCode();
      if (SubType != global::Network.Message.ProductSubType.UnknownProductSubType) hash ^= SubType.GetHashCode();
      if (filter_ != null) hash ^= Filter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uid);
      }
      if (Version.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Version);
      }
      if (Cookie.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Cookie);
      }
      if (ProductType != global::Network.Message.ProductType.Unknown) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ProductType);
      }
      if (SubType != global::Network.Message.ProductSubType.UnknownProductSubType) {
        output.WriteRawTag(40);
        output.WriteEnum((int) SubType);
      }
      if (filter_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Filter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uid);
      }
      if (Version.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Version);
      }
      if (Cookie.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Cookie);
      }
      if (ProductType != global::Network.Message.ProductType.Unknown) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ProductType);
      }
      if (SubType != global::Network.Message.ProductSubType.UnknownProductSubType) {
        output.WriteRawTag(40);
        output.WriteEnum((int) SubType);
      }
      if (filter_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Filter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (Cookie.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cookie);
      }
      if (ProductType != global::Network.Message.ProductType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ProductType);
      }
      if (SubType != global::Network.Message.ProductSubType.UnknownProductSubType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SubType);
      }
      if (filter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Filter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetProductsByCategoryReq other) {
      if (other == null) {
        return;
      }
      if (other.Uid.Length != 0) {
        Uid = other.Uid;
      }
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      if (other.Cookie.Length != 0) {
        Cookie = other.Cookie;
      }
      if (other.ProductType != global::Network.Message.ProductType.Unknown) {
        ProductType = other.ProductType;
      }
      if (other.SubType != global::Network.Message.ProductSubType.UnknownProductSubType) {
        SubType = other.SubType;
      }
      if (other.filter_ != null) {
        if (filter_ == null) {
          Filter = new global::Network.Message.GetProductsFilter();
        }
        Filter.MergeFrom(other.Filter);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Uid = input.ReadString();
            break;
          }
          case 18: {
            Version = input.ReadString();
            break;
          }
          case 26: {
            Cookie = input.ReadString();
            break;
          }
          case 32: {
            ProductType = (global::Network.Message.ProductType) input.ReadEnum();
            break;
          }
          case 40: {
            SubType = (global::Network.Message.ProductSubType) input.ReadEnum();
            break;
          }
          case 50: {
            if (filter_ == null) {
              Filter = new global::Network.Message.GetProductsFilter();
            }
            input.ReadMessage(Filter);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Uid = input.ReadString();
            break;
          }
          case 18: {
            Version = input.ReadString();
            break;
          }
          case 26: {
            Cookie = input.ReadString();
            break;
          }
          case 32: {
            ProductType = (global::Network.Message.ProductType) input.ReadEnum();
            break;
          }
          case 40: {
            SubType = (global::Network.Message.ProductSubType) input.ReadEnum();
            break;
          }
          case 50: {
            if (filter_ == null) {
              Filter = new global::Network.Message.GetProductsFilter();
            }
            input.ReadMessage(Filter);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetProductsByCategoryRsp : pb::IMessage<GetProductsByCategoryRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetProductsByCategoryRsp> _parser = new pb::MessageParser<GetProductsByCategoryRsp>(() => new GetProductsByCategoryRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetProductsByCategoryRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Message.StoreReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetProductsByCategoryRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetProductsByCategoryRsp(GetProductsByCategoryRsp other) : this() {
      cookie_ = other.cookie_;
      isEnd_ = other.isEnd_;
      products_ = other.products_.Clone();
      productType_ = other.productType_;
      subType_ = other.subType_;
      filter_ = other.filter_ != null ? other.filter_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetProductsByCategoryRsp Clone() {
      return new GetProductsByCategoryRsp(this);
    }

    /// <summary>Field number for the "cookie" field.</summary>
    public const int CookieFieldNumber = 1;
    private string cookie_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cookie {
      get { return cookie_; }
      set {
        cookie_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isEnd" field.</summary>
    public const int IsEndFieldNumber = 2;
    private int isEnd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IsEnd {
      get { return isEnd_; }
      set {
        isEnd_ = value;
      }
    }

    /// <summary>Field number for the "products" field.</summary>
    public const int ProductsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Network.Message.Product> _repeated_products_codec
        = pb::FieldCodec.ForMessage(26, global::Network.Message.Product.Parser);
    private readonly pbc::RepeatedField<global::Network.Message.Product> products_ = new pbc::RepeatedField<global::Network.Message.Product>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Network.Message.Product> Products {
      get { return products_; }
    }

    /// <summary>Field number for the "productType" field.</summary>
    public const int ProductTypeFieldNumber = 4;
    private global::Network.Message.ProductType productType_ = global::Network.Message.ProductType.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.ProductType ProductType {
      get { return productType_; }
      set {
        productType_ = value;
      }
    }

    /// <summary>Field number for the "subType" field.</summary>
    public const int SubTypeFieldNumber = 5;
    private global::Network.Message.ProductSubType subType_ = global::Network.Message.ProductSubType.UnknownProductSubType;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.ProductSubType SubType {
      get { return subType_; }
      set {
        subType_ = value;
      }
    }

    /// <summary>Field number for the "filter" field.</summary>
    public const int FilterFieldNumber = 6;
    private global::Network.Message.GetProductsFilter filter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.GetProductsFilter Filter {
      get { return filter_; }
      set {
        filter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetProductsByCategoryRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetProductsByCategoryRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cookie != other.Cookie) return false;
      if (IsEnd != other.IsEnd) return false;
      if(!products_.Equals(other.products_)) return false;
      if (ProductType != other.ProductType) return false;
      if (SubType != other.SubType) return false;
      if (!object.Equals(Filter, other.Filter)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Cookie.Length != 0) hash ^= Cookie.GetHashCode();
      if (IsEnd != 0) hash ^= IsEnd.GetHashCode();
      hash ^= products_.GetHashCode();
      if (ProductType != global::Network.Message.ProductType.Unknown) hash ^= ProductType.GetHashCode();
      if (SubType != global::Network.Message.ProductSubType.UnknownProductSubType) hash ^= SubType.GetHashCode();
      if (filter_ != null) hash ^= Filter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Cookie.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cookie);
      }
      if (IsEnd != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(IsEnd);
      }
      products_.WriteTo(output, _repeated_products_codec);
      if (ProductType != global::Network.Message.ProductType.Unknown) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ProductType);
      }
      if (SubType != global::Network.Message.ProductSubType.UnknownProductSubType) {
        output.WriteRawTag(40);
        output.WriteEnum((int) SubType);
      }
      if (filter_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Filter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Cookie.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cookie);
      }
      if (IsEnd != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(IsEnd);
      }
      products_.WriteTo(ref output, _repeated_products_codec);
      if (ProductType != global::Network.Message.ProductType.Unknown) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ProductType);
      }
      if (SubType != global::Network.Message.ProductSubType.UnknownProductSubType) {
        output.WriteRawTag(40);
        output.WriteEnum((int) SubType);
      }
      if (filter_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Filter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Cookie.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cookie);
      }
      if (IsEnd != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsEnd);
      }
      size += products_.CalculateSize(_repeated_products_codec);
      if (ProductType != global::Network.Message.ProductType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ProductType);
      }
      if (SubType != global::Network.Message.ProductSubType.UnknownProductSubType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SubType);
      }
      if (filter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Filter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetProductsByCategoryRsp other) {
      if (other == null) {
        return;
      }
      if (other.Cookie.Length != 0) {
        Cookie = other.Cookie;
      }
      if (other.IsEnd != 0) {
        IsEnd = other.IsEnd;
      }
      products_.Add(other.products_);
      if (other.ProductType != global::Network.Message.ProductType.Unknown) {
        ProductType = other.ProductType;
      }
      if (other.SubType != global::Network.Message.ProductSubType.UnknownProductSubType) {
        SubType = other.SubType;
      }
      if (other.filter_ != null) {
        if (filter_ == null) {
          Filter = new global::Network.Message.GetProductsFilter();
        }
        Filter.MergeFrom(other.Filter);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Cookie = input.ReadString();
            break;
          }
          case 16: {
            IsEnd = input.ReadInt32();
            break;
          }
          case 26: {
            products_.AddEntriesFrom(input, _repeated_products_codec);
            break;
          }
          case 32: {
            ProductType = (global::Network.Message.ProductType) input.ReadEnum();
            break;
          }
          case 40: {
            SubType = (global::Network.Message.ProductSubType) input.ReadEnum();
            break;
          }
          case 50: {
            if (filter_ == null) {
              Filter = new global::Network.Message.GetProductsFilter();
            }
            input.ReadMessage(Filter);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Cookie = input.ReadString();
            break;
          }
          case 16: {
            IsEnd = input.ReadInt32();
            break;
          }
          case 26: {
            products_.AddEntriesFrom(ref input, _repeated_products_codec);
            break;
          }
          case 32: {
            ProductType = (global::Network.Message.ProductType) input.ReadEnum();
            break;
          }
          case 40: {
            SubType = (global::Network.Message.ProductSubType) input.ReadEnum();
            break;
          }
          case 50: {
            if (filter_ == null) {
              Filter = new global::Network.Message.GetProductsFilter();
            }
            input.ReadMessage(Filter);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Product : pb::IMessage<Product>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Product> _parser = new pb::MessageParser<Product>(() => new Product());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Product> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Message.StoreReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Product() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Product(Product other) : this() {
      id_ = other.id_;
      classifyType_ = other.classifyType_;
      pgcId_ = other.pgcId_;
      itemId_ = other.itemId_;
      batchId_ = other.batchId_;
      type_ = other.type_;
      name_ = other.name_;
      desc_ = other.desc_;
      price_ = other.price_;
      supply_ = other.supply_;
      version_ = other.version_;
      purchaseType_ = other.purchaseType_;
      level_ = other.level_;
      subType_ = other.subType_;
      ownedNum_ = other.ownedNum_;
      soldStatus_ = other.soldStatus_;
      source_ = other.source_;
      extraAttributes_ = other.extraAttributes_ != null ? other.extraAttributes_.Clone() : null;
      extraJumpData_ = other.extraJumpData_ != null ? other.extraJumpData_.Clone() : null;
      canByDirect_ = other.canByDirect_;
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Product Clone() {
      return new Product(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "classifyType" field.</summary>
    public const int ClassifyTypeFieldNumber = 2;
    private int classifyType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ClassifyType {
      get { return classifyType_; }
      set {
        classifyType_ = value;
      }
    }

    /// <summary>Field number for the "pgcId" field.</summary>
    public const int PgcIdFieldNumber = 3;
    private int pgcId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PgcId {
      get { return pgcId_; }
      set {
        pgcId_ = value;
      }
    }

    /// <summary>Field number for the "itemId" field.</summary>
    public const int ItemIdFieldNumber = 4;
    private string itemId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ItemId {
      get { return itemId_; }
      set {
        itemId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "batchId" field.</summary>
    public const int BatchIdFieldNumber = 5;
    private string batchId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BatchId {
      get { return batchId_; }
      set {
        batchId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 6;
    private global::Network.Message.ProductType type_ = global::Network.Message.ProductType.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.ProductType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 7;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "desc" field.</summary>
    public const int DescFieldNumber = 8;
    private string desc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 9;
    private int price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "supply" field.</summary>
    public const int SupplyFieldNumber = 10;
    private int supply_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Supply {
      get { return supply_; }
      set {
        supply_ = value;
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 11;
    private int version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "purchaseType" field.</summary>
    public const int PurchaseTypeFieldNumber = 12;
    private global::Network.Message.PurchaseType purchaseType_ = global::Network.Message.PurchaseType.UnkownPurchaseType;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.PurchaseType PurchaseType {
      get { return purchaseType_; }
      set {
        purchaseType_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 13;
    private global::Network.Message.Level level_ = global::Network.Message.Level.UnkownLevel;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.Level Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "subType" field.</summary>
    public const int SubTypeFieldNumber = 14;
    private global::Network.Message.ProductSubType subType_ = global::Network.Message.ProductSubType.UnknownProductSubType;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.ProductSubType SubType {
      get { return subType_; }
      set {
        subType_ = value;
      }
    }

    /// <summary>Field number for the "ownedNum" field.</summary>
    public const int OwnedNumFieldNumber = 15;
    private int ownedNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OwnedNum {
      get { return ownedNum_; }
      set {
        ownedNum_ = value;
      }
    }

    /// <summary>Field number for the "soldStatus" field.</summary>
    public const int SoldStatusFieldNumber = 16;
    private int soldStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SoldStatus {
      get { return soldStatus_; }
      set {
        soldStatus_ = value;
      }
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 17;
    private global::Network.Message.Source source_ = global::Network.Message.Source.UnkownSource;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.Source Source {
      get { return source_; }
      set {
        source_ = value;
      }
    }

    /// <summary>Field number for the "extraAttributes" field.</summary>
    public const int ExtraAttributesFieldNumber = 18;
    private global::Network.Message.ExtraAttributes extraAttributes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.ExtraAttributes ExtraAttributes {
      get { return extraAttributes_; }
      set {
        extraAttributes_ = value;
      }
    }

    /// <summary>Field number for the "extraJumpData" field.</summary>
    public const int ExtraJumpDataFieldNumber = 19;
    private global::Network.Message.ExtraJumpData extraJumpData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Message.ExtraJumpData ExtraJumpData {
      get { return extraJumpData_; }
      set {
        extraJumpData_ = value;
      }
    }

    /// <summary>Field number for the "canByDirect" field.</summary>
    public const int CanByDirectFieldNumber = 20;
    private bool canByDirect_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CanByDirect {
      get { return canByDirect_; }
      set {
        canByDirect_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 21;
    private int status_;
    /// <summary>
    /// 按钮状态 0:未拥有，1:已拥有，2:商品已售空
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Product);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Product other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ClassifyType != other.ClassifyType) return false;
      if (PgcId != other.PgcId) return false;
      if (ItemId != other.ItemId) return false;
      if (BatchId != other.BatchId) return false;
      if (Type != other.Type) return false;
      if (Name != other.Name) return false;
      if (Desc != other.Desc) return false;
      if (Price != other.Price) return false;
      if (Supply != other.Supply) return false;
      if (Version != other.Version) return false;
      if (PurchaseType != other.PurchaseType) return false;
      if (Level != other.Level) return false;
      if (SubType != other.SubType) return false;
      if (OwnedNum != other.OwnedNum) return false;
      if (SoldStatus != other.SoldStatus) return false;
      if (Source != other.Source) return false;
      if (!object.Equals(ExtraAttributes, other.ExtraAttributes)) return false;
      if (!object.Equals(ExtraJumpData, other.ExtraJumpData)) return false;
      if (CanByDirect != other.CanByDirect) return false;
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (ClassifyType != 0) hash ^= ClassifyType.GetHashCode();
      if (PgcId != 0) hash ^= PgcId.GetHashCode();
      if (ItemId.Length != 0) hash ^= ItemId.GetHashCode();
      if (BatchId.Length != 0) hash ^= BatchId.GetHashCode();
      if (Type != global::Network.Message.ProductType.Unknown) hash ^= Type.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (Price != 0) hash ^= Price.GetHashCode();
      if (Supply != 0) hash ^= Supply.GetHashCode();
      if (Version != 0) hash ^= Version.GetHashCode();
      if (PurchaseType != global::Network.Message.PurchaseType.UnkownPurchaseType) hash ^= PurchaseType.GetHashCode();
      if (Level != global::Network.Message.Level.UnkownLevel) hash ^= Level.GetHashCode();
      if (SubType != global::Network.Message.ProductSubType.UnknownProductSubType) hash ^= SubType.GetHashCode();
      if (OwnedNum != 0) hash ^= OwnedNum.GetHashCode();
      if (SoldStatus != 0) hash ^= SoldStatus.GetHashCode();
      if (Source != global::Network.Message.Source.UnkownSource) hash ^= Source.GetHashCode();
      if (extraAttributes_ != null) hash ^= ExtraAttributes.GetHashCode();
      if (extraJumpData_ != null) hash ^= ExtraJumpData.GetHashCode();
      if (CanByDirect != false) hash ^= CanByDirect.GetHashCode();
      if (Status != 0) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ClassifyType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ClassifyType);
      }
      if (PgcId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PgcId);
      }
      if (ItemId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ItemId);
      }
      if (BatchId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(BatchId);
      }
      if (Type != global::Network.Message.ProductType.Unknown) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Type);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Name);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Desc);
      }
      if (Price != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Price);
      }
      if (Supply != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Supply);
      }
      if (Version != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Version);
      }
      if (PurchaseType != global::Network.Message.PurchaseType.UnkownPurchaseType) {
        output.WriteRawTag(96);
        output.WriteEnum((int) PurchaseType);
      }
      if (Level != global::Network.Message.Level.UnkownLevel) {
        output.WriteRawTag(104);
        output.WriteEnum((int) Level);
      }
      if (SubType != global::Network.Message.ProductSubType.UnknownProductSubType) {
        output.WriteRawTag(112);
        output.WriteEnum((int) SubType);
      }
      if (OwnedNum != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(OwnedNum);
      }
      if (SoldStatus != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(SoldStatus);
      }
      if (Source != global::Network.Message.Source.UnkownSource) {
        output.WriteRawTag(136, 1);
        output.WriteEnum((int) Source);
      }
      if (extraAttributes_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(ExtraAttributes);
      }
      if (extraJumpData_ != null) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(ExtraJumpData);
      }
      if (CanByDirect != false) {
        output.WriteRawTag(160, 1);
        output.WriteBool(CanByDirect);
      }
      if (Status != 0) {
        output.WriteRawTag(168, 1);
        output.WriteInt32(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ClassifyType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ClassifyType);
      }
      if (PgcId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PgcId);
      }
      if (ItemId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ItemId);
      }
      if (BatchId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(BatchId);
      }
      if (Type != global::Network.Message.ProductType.Unknown) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Type);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Name);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Desc);
      }
      if (Price != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Price);
      }
      if (Supply != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Supply);
      }
      if (Version != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Version);
      }
      if (PurchaseType != global::Network.Message.PurchaseType.UnkownPurchaseType) {
        output.WriteRawTag(96);
        output.WriteEnum((int) PurchaseType);
      }
      if (Level != global::Network.Message.Level.UnkownLevel) {
        output.WriteRawTag(104);
        output.WriteEnum((int) Level);
      }
      if (SubType != global::Network.Message.ProductSubType.UnknownProductSubType) {
        output.WriteRawTag(112);
        output.WriteEnum((int) SubType);
      }
      if (OwnedNum != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(OwnedNum);
      }
      if (SoldStatus != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(SoldStatus);
      }
      if (Source != global::Network.Message.Source.UnkownSource) {
        output.WriteRawTag(136, 1);
        output.WriteEnum((int) Source);
      }
      if (extraAttributes_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(ExtraAttributes);
      }
      if (extraJumpData_ != null) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(ExtraJumpData);
      }
      if (CanByDirect != false) {
        output.WriteRawTag(160, 1);
        output.WriteBool(CanByDirect);
      }
      if (Status != 0) {
        output.WriteRawTag(168, 1);
        output.WriteInt32(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (ClassifyType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClassifyType);
      }
      if (PgcId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PgcId);
      }
      if (ItemId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemId);
      }
      if (BatchId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BatchId);
      }
      if (Type != global::Network.Message.ProductType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (Price != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Price);
      }
      if (Supply != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Supply);
      }
      if (Version != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Version);
      }
      if (PurchaseType != global::Network.Message.PurchaseType.UnkownPurchaseType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PurchaseType);
      }
      if (Level != global::Network.Message.Level.UnkownLevel) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Level);
      }
      if (SubType != global::Network.Message.ProductSubType.UnknownProductSubType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SubType);
      }
      if (OwnedNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OwnedNum);
      }
      if (SoldStatus != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(SoldStatus);
      }
      if (Source != global::Network.Message.Source.UnkownSource) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) Source);
      }
      if (extraAttributes_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ExtraAttributes);
      }
      if (extraJumpData_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ExtraJumpData);
      }
      if (CanByDirect != false) {
        size += 2 + 1;
      }
      if (Status != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Product other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.ClassifyType != 0) {
        ClassifyType = other.ClassifyType;
      }
      if (other.PgcId != 0) {
        PgcId = other.PgcId;
      }
      if (other.ItemId.Length != 0) {
        ItemId = other.ItemId;
      }
      if (other.BatchId.Length != 0) {
        BatchId = other.BatchId;
      }
      if (other.Type != global::Network.Message.ProductType.Unknown) {
        Type = other.Type;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      if (other.Price != 0) {
        Price = other.Price;
      }
      if (other.Supply != 0) {
        Supply = other.Supply;
      }
      if (other.Version != 0) {
        Version = other.Version;
      }
      if (other.PurchaseType != global::Network.Message.PurchaseType.UnkownPurchaseType) {
        PurchaseType = other.PurchaseType;
      }
      if (other.Level != global::Network.Message.Level.UnkownLevel) {
        Level = other.Level;
      }
      if (other.SubType != global::Network.Message.ProductSubType.UnknownProductSubType) {
        SubType = other.SubType;
      }
      if (other.OwnedNum != 0) {
        OwnedNum = other.OwnedNum;
      }
      if (other.SoldStatus != 0) {
        SoldStatus = other.SoldStatus;
      }
      if (other.Source != global::Network.Message.Source.UnkownSource) {
        Source = other.Source;
      }
      if (other.extraAttributes_ != null) {
        if (extraAttributes_ == null) {
          ExtraAttributes = new global::Network.Message.ExtraAttributes();
        }
        ExtraAttributes.MergeFrom(other.ExtraAttributes);
      }
      if (other.extraJumpData_ != null) {
        if (extraJumpData_ == null) {
          ExtraJumpData = new global::Network.Message.ExtraJumpData();
        }
        ExtraJumpData.MergeFrom(other.ExtraJumpData);
      }
      if (other.CanByDirect != false) {
        CanByDirect = other.CanByDirect;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            ClassifyType = input.ReadInt32();
            break;
          }
          case 24: {
            PgcId = input.ReadInt32();
            break;
          }
          case 34: {
            ItemId = input.ReadString();
            break;
          }
          case 42: {
            BatchId = input.ReadString();
            break;
          }
          case 48: {
            Type = (global::Network.Message.ProductType) input.ReadEnum();
            break;
          }
          case 58: {
            Name = input.ReadString();
            break;
          }
          case 66: {
            Desc = input.ReadString();
            break;
          }
          case 72: {
            Price = input.ReadInt32();
            break;
          }
          case 80: {
            Supply = input.ReadInt32();
            break;
          }
          case 88: {
            Version = input.ReadInt32();
            break;
          }
          case 96: {
            PurchaseType = (global::Network.Message.PurchaseType) input.ReadEnum();
            break;
          }
          case 104: {
            Level = (global::Network.Message.Level) input.ReadEnum();
            break;
          }
          case 112: {
            SubType = (global::Network.Message.ProductSubType) input.ReadEnum();
            break;
          }
          case 120: {
            OwnedNum = input.ReadInt32();
            break;
          }
          case 128: {
            SoldStatus = input.ReadInt32();
            break;
          }
          case 136: {
            Source = (global::Network.Message.Source) input.ReadEnum();
            break;
          }
          case 146: {
            if (extraAttributes_ == null) {
              ExtraAttributes = new global::Network.Message.ExtraAttributes();
            }
            input.ReadMessage(ExtraAttributes);
            break;
          }
          case 154: {
            if (extraJumpData_ == null) {
              ExtraJumpData = new global::Network.Message.ExtraJumpData();
            }
            input.ReadMessage(ExtraJumpData);
            break;
          }
          case 160: {
            CanByDirect = input.ReadBool();
            break;
          }
          case 168: {
            Status = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            ClassifyType = input.ReadInt32();
            break;
          }
          case 24: {
            PgcId = input.ReadInt32();
            break;
          }
          case 34: {
            ItemId = input.ReadString();
            break;
          }
          case 42: {
            BatchId = input.ReadString();
            break;
          }
          case 48: {
            Type = (global::Network.Message.ProductType) input.ReadEnum();
            break;
          }
          case 58: {
            Name = input.ReadString();
            break;
          }
          case 66: {
            Desc = input.ReadString();
            break;
          }
          case 72: {
            Price = input.ReadInt32();
            break;
          }
          case 80: {
            Supply = input.ReadInt32();
            break;
          }
          case 88: {
            Version = input.ReadInt32();
            break;
          }
          case 96: {
            PurchaseType = (global::Network.Message.PurchaseType) input.ReadEnum();
            break;
          }
          case 104: {
            Level = (global::Network.Message.Level) input.ReadEnum();
            break;
          }
          case 112: {
            SubType = (global::Network.Message.ProductSubType) input.ReadEnum();
            break;
          }
          case 120: {
            OwnedNum = input.ReadInt32();
            break;
          }
          case 128: {
            SoldStatus = input.ReadInt32();
            break;
          }
          case 136: {
            Source = (global::Network.Message.Source) input.ReadEnum();
            break;
          }
          case 146: {
            if (extraAttributes_ == null) {
              ExtraAttributes = new global::Network.Message.ExtraAttributes();
            }
            input.ReadMessage(ExtraAttributes);
            break;
          }
          case 154: {
            if (extraJumpData_ == null) {
              ExtraJumpData = new global::Network.Message.ExtraJumpData();
            }
            input.ReadMessage(ExtraJumpData);
            break;
          }
          case 160: {
            CanByDirect = input.ReadBool();
            break;
          }
          case 168: {
            Status = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExtraAttributes : pb::IMessage<ExtraAttributes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExtraAttributes> _parser = new pb::MessageParser<ExtraAttributes>(() => new ExtraAttributes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExtraAttributes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Message.StoreReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtraAttributes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtraAttributes(ExtraAttributes other) : this() {
      setNum_ = other.setNum_;
      discount_ = other.discount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtraAttributes Clone() {
      return new ExtraAttributes(this);
    }

    /// <summary>Field number for the "setNum" field.</summary>
    public const int SetNumFieldNumber = 1;
    private int setNum_;
    /// <summary>
    /// 可重复使用次数或者套装内的商品个数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SetNum {
      get { return setNum_; }
      set {
        setNum_ = value;
      }
    }

    /// <summary>Field number for the "discount" field.</summary>
    public const int DiscountFieldNumber = 2;
    private int discount_;
    /// <summary>
    /// 首次购买折扣
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Discount {
      get { return discount_; }
      set {
        discount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExtraAttributes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExtraAttributes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SetNum != other.SetNum) return false;
      if (Discount != other.Discount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SetNum != 0) hash ^= SetNum.GetHashCode();
      if (Discount != 0) hash ^= Discount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SetNum != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SetNum);
      }
      if (Discount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Discount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SetNum != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SetNum);
      }
      if (Discount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Discount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SetNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SetNum);
      }
      if (Discount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Discount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExtraAttributes other) {
      if (other == null) {
        return;
      }
      if (other.SetNum != 0) {
        SetNum = other.SetNum;
      }
      if (other.Discount != 0) {
        Discount = other.Discount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SetNum = input.ReadInt32();
            break;
          }
          case 16: {
            Discount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SetNum = input.ReadInt32();
            break;
          }
          case 16: {
            Discount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetProductsFilter : pb::IMessage<GetProductsFilter>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetProductsFilter> _parser = new pb::MessageParser<GetProductsFilter>(() => new GetProductsFilter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetProductsFilter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Message.StoreReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetProductsFilter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetProductsFilter(GetProductsFilter other) : this() {
      onlyCanByDirect_ = other.onlyCanByDirect_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetProductsFilter Clone() {
      return new GetProductsFilter(this);
    }

    /// <summary>Field number for the "onlyCanByDirect" field.</summary>
    public const int OnlyCanByDirectFieldNumber = 1;
    private bool onlyCanByDirect_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OnlyCanByDirect {
      get { return onlyCanByDirect_; }
      set {
        onlyCanByDirect_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetProductsFilter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetProductsFilter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OnlyCanByDirect != other.OnlyCanByDirect) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OnlyCanByDirect != false) hash ^= OnlyCanByDirect.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OnlyCanByDirect != false) {
        output.WriteRawTag(8);
        output.WriteBool(OnlyCanByDirect);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OnlyCanByDirect != false) {
        output.WriteRawTag(8);
        output.WriteBool(OnlyCanByDirect);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OnlyCanByDirect != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetProductsFilter other) {
      if (other == null) {
        return;
      }
      if (other.OnlyCanByDirect != false) {
        OnlyCanByDirect = other.OnlyCanByDirect;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OnlyCanByDirect = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OnlyCanByDirect = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExtraJumpData : pb::IMessage<ExtraJumpData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExtraJumpData> _parser = new pb::MessageParser<ExtraJumpData>(() => new ExtraJumpData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExtraJumpData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Message.StoreReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtraJumpData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtraJumpData(ExtraJumpData other) : this() {
      downtownTags_ = other.downtownTags_.Clone();
      rotaryTags_ = other.rotaryTags_.Clone();
      blindBoxTags_ = other.blindBoxTags_.Clone();
      taskTags_ = other.taskTags_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtraJumpData Clone() {
      return new ExtraJumpData(this);
    }

    /// <summary>Field number for the "downtownTags" field.</summary>
    public const int DowntownTagsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_downtownTags_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> downtownTags_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> DowntownTags {
      get { return downtownTags_; }
    }

    /// <summary>Field number for the "rotaryTags" field.</summary>
    public const int RotaryTagsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_rotaryTags_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> rotaryTags_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> RotaryTags {
      get { return rotaryTags_; }
    }

    /// <summary>Field number for the "blindBoxTags" field.</summary>
    public const int BlindBoxTagsFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_blindBoxTags_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> blindBoxTags_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> BlindBoxTags {
      get { return blindBoxTags_; }
    }

    /// <summary>Field number for the "taskTags" field.</summary>
    public const int TaskTagsFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_taskTags_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> taskTags_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> TaskTags {
      get { return taskTags_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExtraJumpData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExtraJumpData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!downtownTags_.Equals(other.downtownTags_)) return false;
      if(!rotaryTags_.Equals(other.rotaryTags_)) return false;
      if(!blindBoxTags_.Equals(other.blindBoxTags_)) return false;
      if(!taskTags_.Equals(other.taskTags_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= downtownTags_.GetHashCode();
      hash ^= rotaryTags_.GetHashCode();
      hash ^= blindBoxTags_.GetHashCode();
      hash ^= taskTags_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      downtownTags_.WriteTo(output, _repeated_downtownTags_codec);
      rotaryTags_.WriteTo(output, _repeated_rotaryTags_codec);
      blindBoxTags_.WriteTo(output, _repeated_blindBoxTags_codec);
      taskTags_.WriteTo(output, _repeated_taskTags_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      downtownTags_.WriteTo(ref output, _repeated_downtownTags_codec);
      rotaryTags_.WriteTo(ref output, _repeated_rotaryTags_codec);
      blindBoxTags_.WriteTo(ref output, _repeated_blindBoxTags_codec);
      taskTags_.WriteTo(ref output, _repeated_taskTags_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += downtownTags_.CalculateSize(_repeated_downtownTags_codec);
      size += rotaryTags_.CalculateSize(_repeated_rotaryTags_codec);
      size += blindBoxTags_.CalculateSize(_repeated_blindBoxTags_codec);
      size += taskTags_.CalculateSize(_repeated_taskTags_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExtraJumpData other) {
      if (other == null) {
        return;
      }
      downtownTags_.Add(other.downtownTags_);
      rotaryTags_.Add(other.rotaryTags_);
      blindBoxTags_.Add(other.blindBoxTags_);
      taskTags_.Add(other.taskTags_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            downtownTags_.AddEntriesFrom(input, _repeated_downtownTags_codec);
            break;
          }
          case 18: {
            rotaryTags_.AddEntriesFrom(input, _repeated_rotaryTags_codec);
            break;
          }
          case 26: {
            blindBoxTags_.AddEntriesFrom(input, _repeated_blindBoxTags_codec);
            break;
          }
          case 34: {
            taskTags_.AddEntriesFrom(input, _repeated_taskTags_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            downtownTags_.AddEntriesFrom(ref input, _repeated_downtownTags_codec);
            break;
          }
          case 18: {
            rotaryTags_.AddEntriesFrom(ref input, _repeated_rotaryTags_codec);
            break;
          }
          case 26: {
            blindBoxTags_.AddEntriesFrom(ref input, _repeated_blindBoxTags_codec);
            break;
          }
          case 34: {
            taskTags_.AddEntriesFrom(ref input, _repeated_taskTags_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
