
//------------------------------------------------------------------------------
// <auto-generated>
// This Script Generate By Tools.
// 工具：BudTools -> 道具工具
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameData.Config
{
	public enum NodeModelType
	{
		None = 0,
		SimpleShape = 1,
		Terrain = 2,
		Combine = 3,
		SpawnPoint = 5,
		MovePoint = 7,
		WinReachEngFlag = 8,
		CollectAllStar = 9,
		SwitchBtn = 10,
		PointLight = 11,
		SpotLight = 12,
		DText = 13,
		SensorBox = 14,
		PortalButton = 16,
		PortalPoint = 17,
		PGCStone = 18,
		PGCPlant = 19,
		PGCEffect = 20,
		MusicPad = 21,
		ShotPhoto = 22,
		UGCClothes = 23,
		WaterCube = 24,
		IceCube = 25,
		SnowCube = 26,
		Prop = 27,
		TrapBox = 28,
		TrapSpawn = 29,
		InteractiveBoard = 30,
		AttentionButton = 31,
		LikeButton = 32,
		FavoriteButton = 33,
		PGCNode = 34,
		PreviewModel = 35,
		AIBuddyInMap = 36,
		CameraLandMark = 37,
		TheatreTrigger = 38,
		AIYandereCharacter = 1001,
		AIYandereDoor = 1002,
		AIYandereTriggerArea = 1003,
		AIYandereMainDoor = 1004,
		AIYandereTargetPoint = 1005,
		AIYandereRunTargetPoint = 1006,
		AISofa = 1007,
		AITV = 1008,
		AILight = 1009,
		AIBathRoom = 1010,
		Computer = 1011,
		AIHospitalDoor = 2000,
		AIHospitalFileCabinet = 2001,
		AIHospitalMedicineCabinet = 2002,
		AIHospitalRoomDoor = 2003,
		AIHospitalToilet = 2004,
		AIHospitalCorridorDoor = 2005,
		AIHospitalReceptionDoor = 2006,
		AIHospitalChair = 2007,
		AIHospitalEquipment = 2008,
		AIHospitalBed = 2009,
		AIHospitalLamp = 2010,
		AIHospitalMedicine = 2011,
		AIHospitalCharacter = 2012,
		AIHospitalDeanCabinet = 2013,
		AIHospitalMainDoor = 2014,
		AIHospitalBrokeLight = 2015,
		AIHospitalTargetPoint = 2016,
		AIHospital_Photo = 2017,
		AIParkSeesaw = 3001,
		AIParkSlide = 3002,
		AIParkSwing = 3003,
		AIParkTrojanhorse = 3004,
		AIParkStage = 3005,
		AIParkInstrument = 3006,
		AIParkSeesaw_chair = 3007, //椅子给AIParkSeesaw用
		AIParkSwing_chair = 3008, //椅子给AIParkSwing用
		AIParkTrojanhorse_chair = 3009, //椅子给AIParkTrojanhorse用
		AIParkBench = 3010, //长椅
		AIParkBench_chair = 3011, //椅子给AIParkBench用,
		AIPark_Photo = 3020,//AIPark 照片墙1
		//AIPark_Photo2 = 3021,//AIPark 照片墙1
	}
}
