// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: map_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb.Map {

  /// <summary>Holder for reflection information generated from map_data.proto</summary>
  public static partial class MapDataReflection {

    #region Descriptor
    /// <summary>File descriptor for map_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MapDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5tYXBfZGF0YS5wcm90bxIGcGIubWFwGg9ub2RlX2RhdGEucHJvdG8inwIK",
            "CFBNYXBEYXRhEioKCmJhc2ljX2RhdGEYASABKAsyFi5wYi5tYXAuUEdhbWVC",
            "YXNpY0RhdGESKAoJcHJvcF9kYXRhGAIgASgLMhUucGIubWFwLlBHYW1lUHJv",
            "cERhdGESLgoMc2V0dGluZ19kYXRhGAMgASgLMhgucGIubWFwLlBHYW1lU2V0",
            "dGluZ0RhdGESLwoLdWdjbWF0X2RhdGEYBCABKAsyGi5wYi5tYXAuUEdhbWVV",
            "R0NNYXRNYXBEYXRhEjIKDXVnY19pdGVtX2RhdGEYBSABKAsyGy5wYi5tYXAu",
            "UEdhbWVVR0NJdGVtTWFwRGF0YRIoCglobG9kX2RhdGEYBiABKAsyFS5wYi5t",
            "YXAuUEdhbWVITE9ERGF0YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Pb.Map.NodeDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Map.PMapData), global::Pb.Map.PMapData.Parser, new[]{ "BasicData", "PropData", "SettingData", "UgcmatData", "UgcItemData", "HlodData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PMapData : pb::IMessage<PMapData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PMapData> _parser = new pb::MessageParser<PMapData>(() => new PMapData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PMapData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Map.MapDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PMapData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PMapData(PMapData other) : this() {
      basicData_ = other.basicData_ != null ? other.basicData_.Clone() : null;
      propData_ = other.propData_ != null ? other.propData_.Clone() : null;
      settingData_ = other.settingData_ != null ? other.settingData_.Clone() : null;
      ugcmatData_ = other.ugcmatData_ != null ? other.ugcmatData_.Clone() : null;
      ugcItemData_ = other.ugcItemData_ != null ? other.ugcItemData_.Clone() : null;
      hlodData_ = other.hlodData_ != null ? other.hlodData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PMapData Clone() {
      return new PMapData(this);
    }

    /// <summary>Field number for the "basic_data" field.</summary>
    public const int BasicDataFieldNumber = 1;
    private global::Pb.Map.PGameBasicData basicData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.Map.PGameBasicData BasicData {
      get { return basicData_; }
      set {
        basicData_ = value;
      }
    }

    /// <summary>Field number for the "prop_data" field.</summary>
    public const int PropDataFieldNumber = 2;
    private global::Pb.Map.PGamePropData propData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.Map.PGamePropData PropData {
      get { return propData_; }
      set {
        propData_ = value;
      }
    }

    /// <summary>Field number for the "setting_data" field.</summary>
    public const int SettingDataFieldNumber = 3;
    private global::Pb.Map.PGameSettingData settingData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.Map.PGameSettingData SettingData {
      get { return settingData_; }
      set {
        settingData_ = value;
      }
    }

    /// <summary>Field number for the "ugcmat_data" field.</summary>
    public const int UgcmatDataFieldNumber = 4;
    private global::Pb.Map.PGameUGCMatMapData ugcmatData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.Map.PGameUGCMatMapData UgcmatData {
      get { return ugcmatData_; }
      set {
        ugcmatData_ = value;
      }
    }

    /// <summary>Field number for the "ugc_item_data" field.</summary>
    public const int UgcItemDataFieldNumber = 5;
    private global::Pb.Map.PGameUGCItemMapData ugcItemData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.Map.PGameUGCItemMapData UgcItemData {
      get { return ugcItemData_; }
      set {
        ugcItemData_ = value;
      }
    }

    /// <summary>Field number for the "hlod_data" field.</summary>
    public const int HlodDataFieldNumber = 6;
    private global::Pb.Map.PGameHLODData hlodData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.Map.PGameHLODData HlodData {
      get { return hlodData_; }
      set {
        hlodData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PMapData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PMapData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BasicData, other.BasicData)) return false;
      if (!object.Equals(PropData, other.PropData)) return false;
      if (!object.Equals(SettingData, other.SettingData)) return false;
      if (!object.Equals(UgcmatData, other.UgcmatData)) return false;
      if (!object.Equals(UgcItemData, other.UgcItemData)) return false;
      if (!object.Equals(HlodData, other.HlodData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (basicData_ != null) hash ^= BasicData.GetHashCode();
      if (propData_ != null) hash ^= PropData.GetHashCode();
      if (settingData_ != null) hash ^= SettingData.GetHashCode();
      if (ugcmatData_ != null) hash ^= UgcmatData.GetHashCode();
      if (ugcItemData_ != null) hash ^= UgcItemData.GetHashCode();
      if (hlodData_ != null) hash ^= HlodData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (basicData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BasicData);
      }
      if (propData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PropData);
      }
      if (settingData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SettingData);
      }
      if (ugcmatData_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(UgcmatData);
      }
      if (ugcItemData_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(UgcItemData);
      }
      if (hlodData_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(HlodData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (basicData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BasicData);
      }
      if (propData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PropData);
      }
      if (settingData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SettingData);
      }
      if (ugcmatData_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(UgcmatData);
      }
      if (ugcItemData_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(UgcItemData);
      }
      if (hlodData_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(HlodData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (basicData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BasicData);
      }
      if (propData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PropData);
      }
      if (settingData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SettingData);
      }
      if (ugcmatData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UgcmatData);
      }
      if (ugcItemData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UgcItemData);
      }
      if (hlodData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HlodData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PMapData other) {
      if (other == null) {
        return;
      }
      if (other.basicData_ != null) {
        if (basicData_ == null) {
          BasicData = new global::Pb.Map.PGameBasicData();
        }
        BasicData.MergeFrom(other.BasicData);
      }
      if (other.propData_ != null) {
        if (propData_ == null) {
          PropData = new global::Pb.Map.PGamePropData();
        }
        PropData.MergeFrom(other.PropData);
      }
      if (other.settingData_ != null) {
        if (settingData_ == null) {
          SettingData = new global::Pb.Map.PGameSettingData();
        }
        SettingData.MergeFrom(other.SettingData);
      }
      if (other.ugcmatData_ != null) {
        if (ugcmatData_ == null) {
          UgcmatData = new global::Pb.Map.PGameUGCMatMapData();
        }
        UgcmatData.MergeFrom(other.UgcmatData);
      }
      if (other.ugcItemData_ != null) {
        if (ugcItemData_ == null) {
          UgcItemData = new global::Pb.Map.PGameUGCItemMapData();
        }
        UgcItemData.MergeFrom(other.UgcItemData);
      }
      if (other.hlodData_ != null) {
        if (hlodData_ == null) {
          HlodData = new global::Pb.Map.PGameHLODData();
        }
        HlodData.MergeFrom(other.HlodData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (basicData_ == null) {
              BasicData = new global::Pb.Map.PGameBasicData();
            }
            input.ReadMessage(BasicData);
            break;
          }
          case 18: {
            if (propData_ == null) {
              PropData = new global::Pb.Map.PGamePropData();
            }
            input.ReadMessage(PropData);
            break;
          }
          case 26: {
            if (settingData_ == null) {
              SettingData = new global::Pb.Map.PGameSettingData();
            }
            input.ReadMessage(SettingData);
            break;
          }
          case 34: {
            if (ugcmatData_ == null) {
              UgcmatData = new global::Pb.Map.PGameUGCMatMapData();
            }
            input.ReadMessage(UgcmatData);
            break;
          }
          case 42: {
            if (ugcItemData_ == null) {
              UgcItemData = new global::Pb.Map.PGameUGCItemMapData();
            }
            input.ReadMessage(UgcItemData);
            break;
          }
          case 50: {
            if (hlodData_ == null) {
              HlodData = new global::Pb.Map.PGameHLODData();
            }
            input.ReadMessage(HlodData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (basicData_ == null) {
              BasicData = new global::Pb.Map.PGameBasicData();
            }
            input.ReadMessage(BasicData);
            break;
          }
          case 18: {
            if (propData_ == null) {
              PropData = new global::Pb.Map.PGamePropData();
            }
            input.ReadMessage(PropData);
            break;
          }
          case 26: {
            if (settingData_ == null) {
              SettingData = new global::Pb.Map.PGameSettingData();
            }
            input.ReadMessage(SettingData);
            break;
          }
          case 34: {
            if (ugcmatData_ == null) {
              UgcmatData = new global::Pb.Map.PGameUGCMatMapData();
            }
            input.ReadMessage(UgcmatData);
            break;
          }
          case 42: {
            if (ugcItemData_ == null) {
              UgcItemData = new global::Pb.Map.PGameUGCItemMapData();
            }
            input.ReadMessage(UgcItemData);
            break;
          }
          case 50: {
            if (hlodData_ == null) {
              HlodData = new global::Pb.Map.PGameHLODData();
            }
            input.ReadMessage(HlodData);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
