//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	public sealed partial class AnimationConfigTable : EsRowDataTable
	{
		[SerializeField]
		private List<AnimationConfig> _dataList = new List<AnimationConfig>();

		private Dictionary<string, AnimationConfig> _dataMap;
		public Dictionary<string, AnimationConfig> DataMap => _dataMap;
		public List<AnimationConfig> DataList => _dataList;

		public AnimationConfig Get(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
		public AnimationConfig this[string key] => _dataMap.TryGetValue(key, out var v) ? v : null;

		protected override void OnDeserialized()
		{
			_dataMap = new Dictionary<string, AnimationConfig>(_dataList.Count);
			foreach (var data in _dataList)
			{
				_dataMap.Add(data.AnimationName, data);
				(data as ISerializationCallbackReceiver).OnAfterDeserialize();
			}
			PostInit();
		}

		partial void PostInit();
	}
}
