//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class AnimationConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _AnimationName;
		public string AnimationName => _AnimationName;

		[SerializeField]
		private int _layerIndex;
		public int layerIndex => _layerIndex;

		[SerializeField]
		private bool _IsLoad;
		public bool IsLoad => _IsLoad;

		[SerializeField]
		private string _LoadPath;
		public string LoadPath => _LoadPath;


		public AnimationConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _AnimationName);
			EsParser.TryParse(cells[column++], out _layerIndex);
			EsParser.TryParse(cells[column++], out _IsLoad);
			EsParser.TryParse(cells[column++], out _LoadPath);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}