//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	public sealed partial class CabinDefActionConfigTable : EsRowDataTable
	{
		[SerializeField]
		private List<CabinDefActionConfig> _dataList = new List<CabinDefActionConfig>();

		private Dictionary<string, CabinDefActionConfig> _dataMap;
		public Dictionary<string, CabinDefActionConfig> DataMap => _dataMap;
		public List<CabinDefActionConfig> DataList => _dataList;

		public CabinDefActionConfig Get(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
		public CabinDefActionConfig this[string key] => _dataMap.TryGetValue(key, out var v) ? v : null;

		protected override void OnDeserialized()
		{
			_dataMap = new Dictionary<string, CabinDefActionConfig>(_dataList.Count);
			foreach (var data in _dataList)
			{
				_dataMap.Add(data.EmoUIID, data);
				(data as ISerializationCallbackReceiver).OnAfterDeserialize();
			}
			PostInit();
		}

		partial void PostInit();
	}
}
