//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class CabinDefCharacterConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _ID;
		public string ID => _ID;

		[SerializeField]
		private string _tokenID;
		public string tokenID => _tokenID;

		[SerializeField]
		private string _StandLoop;
		public string StandLoop => _StandLoop;

		[SerializeField]
		private string _StandSole;
		public string StandSole => _StandSole;

		[SerializeField]
		private string _ActiveInfo;
		public string ActiveInfo => _ActiveInfo;

		[SerializeField]
		private string _CommandInfo;
		public string CommandInfo => _CommandInfo;

		[SerializeField]
		private string _PoseAnimID;
		public string PoseAnimID => _PoseAnimID;

		[SerializeField]
		private int _CardColorID;
		public int CardColorID => _CardColorID;

		[SerializeField]
		private UnityEngine.Vector3 _CardSize;
		public UnityEngine.Vector3 CardSize => _CardSize;

		[SerializeField]
		private UnityEngine.Vector3 _CardPos;
		public UnityEngine.Vector3 CardPos => _CardPos;


		public CabinDefCharacterConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _ID);
			EsParser.TryParse(cells[column++], out _tokenID);
			EsParser.TryParse(cells[column++], out _StandLoop);
			EsParser.TryParse(cells[column++], out _StandSole);
			EsParser.TryParse(cells[column++], out _ActiveInfo);
			EsParser.TryParse(cells[column++], out _CommandInfo);
			EsParser.TryParse(cells[column++], out _PoseAnimID);
			EsParser.TryParse(cells[column++], out _CardColorID);
			_CardSize = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _CardSize, cells[column++]);
			_CardPos = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _CardPos, cells[column++]);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}