//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class CabinDefActionConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _EmoUIID;
		public string EmoUIID => _EmoUIID;

		[SerializeField]
		private string _Cover;
		public string Cover => _Cover;

		[SerializeField]
		private string _Command;
		public string Command => _Command;


		public CabinDefActionConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _EmoUIID);
			EsParser.TryParse(cells[column++], out _Cover);
			EsParser.TryParse(cells[column++], out _Command);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}