//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	public sealed partial class CameraModeResourceTable : EsRowDataTable
	{
		[SerializeField]
		private List<CameraModeResource> _dataList = new List<CameraModeResource>();

		private Dictionary<int, CameraModeResource> _dataMap;
		public Dictionary<int, CameraModeResource> DataMap => _dataMap;
		public List<CameraModeResource> DataList => _dataList;

		public CameraModeResource Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
		public CameraModeResource this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

		protected override void OnDeserialized()
		{
			_dataMap = new Dictionary<int, CameraModeResource>(_dataList.Count);
			foreach (var data in _dataList)
			{
				_dataMap.Add(data.id, data);
				(data as ISerializationCallbackReceiver).OnAfterDeserialize();
			}
			PostInit();
		}

		partial void PostInit();
	}
}
