//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class CameraSelfiePose : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _id;
		public string id => _id;

		[SerializeField]
		private string _name;
		public string name => _name;

		[SerializeField]
		private string _type;
		public string type => _type;

		[SerializeField]
		private int _price;
		public int price => _price;

		[SerializeField]
		private int _currency;
		public int currency => _currency;

		[SerializeField]
		private int _gainType;
		public int gainType => _gainType;

		[SerializeField]
		private int _jumpScene;
		public int jumpScene => _jumpScene;

		[SerializeField]
		private string _iconString;
		public string iconString => _iconString;

		[SerializeField]
		private string _resourcePath;
		public string resourcePath => _resourcePath;

		[SerializeField]
		private int _stickHand;
		public int stickHand => _stickHand;

		[SerializeField]
		private UnityEngine.Vector3 _stickRot;
		public UnityEngine.Vector3 stickRot => _stickRot;

		[SerializeField]
		private bool _moveable;
		public bool moveable => _moveable;

		[SerializeField]
		private UnityEngine.Vector3 _cameraPos;
		public UnityEngine.Vector3 cameraPos => _cameraPos;

		[SerializeField]
		private UnityEngine.Vector3 _cameraRot;
		public UnityEngine.Vector3 cameraRot => _cameraRot;


		public CameraSelfiePose()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _id);
			EsParser.TryParse(cells[column++], out _name);
			EsParser.TryParse(cells[column++], out _type);
			EsParser.TryParse(cells[column++], out _price);
			EsParser.TryParse(cells[column++], out _currency);
			EsParser.TryParse(cells[column++], out _gainType);
			EsParser.TryParse(cells[column++], out _jumpScene);
			EsParser.TryParse(cells[column++], out _iconString);
			EsParser.TryParse(cells[column++], out _resourcePath);
			EsParser.TryParse(cells[column++], out _stickHand);
			_stickRot = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _stickRot, cells[column++]);
			EsParser.TryParse(cells[column++], out _moveable);
			_cameraPos = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _cameraPos, cells[column++]);
			_cameraRot = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _cameraRot, cells[column++]);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}