//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class CameraModeResource : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _id;
		public int id => _id;

		[SerializeField]
		private string _name;
		public string name => _name;

		[SerializeField]
		private string _type;
		public string type => _type;

		[SerializeField]
		private string _iconString;
		public string iconString => _iconString;

		[SerializeField]
		private string _resourcePath;
		public string resourcePath => _resourcePath;

		[SerializeField]
		private bool _isVIP;
		public bool isVIP => _isVIP;

		[SerializeField]
		private string _extraValue;
		public string extraValue => _extraValue;


		public CameraModeResource()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _id);
			EsParser.TryParse(cells[column++], out _name);
			EsParser.TryParse(cells[column++], out _type);
			EsParser.TryParse(cells[column++], out _iconString);
			EsParser.TryParse(cells[column++], out _resourcePath);
			EsParser.TryParse(cells[column++], out _isVIP);
			EsParser.TryParse(cells[column++], out _extraValue);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}