//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class CreatorRewardConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _Id;
		public int Id => _Id;

		[SerializeField]
		private int _Category;
		public int Category => _Category;

		[SerializeField]
		private int _Level;
		public int Level => _Level;

		[SerializeField]
		private int _TitleId;
		public int TitleId => _TitleId;

		[SerializeField]
		private string _Badge;
		public string Badge => _Badge;

		[SerializeField]
		private int _ThemeId;
		public int ThemeId => _ThemeId;

		[SerializeField]
		private int _ActionId;
		public int ActionId => _ActionId;

		[SerializeField]
		private string _ScoreFrameName;
		public string ScoreFrameName => _ScoreFrameName;

		[SerializeField]
		private int _HeadFrameId;
		public int HeadFrameId => _HeadFrameId;


		public CreatorRewardConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _Id);
			EsParser.TryParse(cells[column++], out _Category);
			EsParser.TryParse(cells[column++], out _Level);
			EsParser.TryParse(cells[column++], out _TitleId);
			EsParser.TryParse(cells[column++], out _Badge);
			EsParser.TryParse(cells[column++], out _ThemeId);
			EsParser.TryParse(cells[column++], out _ActionId);
			EsParser.TryParse(cells[column++], out _ScoreFrameName);
			EsParser.TryParse(cells[column++], out _HeadFrameId);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}