//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections;
using EasySpreadsheet;

namespace Es
{
	public partial class DataTables
	{
		public static DataTables Instance => s_instance;

		private Dictionary<string, EsRowDataTable> _cfgs;
		public Dictionary<string, EsRowDataTable> Cfgs => _cfgs;
		public ActivityConfigTable ActivityConfigTable {get; private set;}
		public AnimationConfigTable AnimationConfigTable {get; private set;}
		public AnniversaryCalendarViewTable AnniversaryCalendarViewTable {get; private set;}
		public AvatarColorDataTable AvatarColorDataTable {get; private set;}
		public AvatarCommonDataTable AvatarCommonDataTable {get; private set;}
		public BundleConfigTable BundleConfigTable {get; private set;}
		public CabinDefActionConfigTable CabinDefActionConfigTable {get; private set;}
		public CabinDefCharacterConfigTable CabinDefCharacterConfigTable {get; private set;}
		public CabinPgcEmoConfigTable CabinPgcEmoConfigTable {get; private set;}
		public CabinUgcAnimBgmConfigTable CabinUgcAnimBgmConfigTable {get; private set;}
		public CameraModeResourceTable CameraModeResourceTable {get; private set;}
		public CameraSelfiePoseTable CameraSelfiePoseTable {get; private set;}
		public ClothesTemplateTable ClothesTemplateTable {get; private set;}
		public ColorDataConfigTable ColorDataConfigTable {get; private set;}
		public CreatorRewardConfigTable CreatorRewardConfigTable {get; private set;}
		public DraftBoxCardColorConfigTable DraftBoxCardColorConfigTable {get; private set;}
		public EmoAniConfigTable EmoAniConfigTable {get; private set;}
		public EmoUIConfigTable EmoUIConfigTable {get; private set;}
		public FeatAniConfigTable FeatAniConfigTable {get; private set;}
		public GameBgAudioDataTable GameBgAudioDataTable {get; private set;}
		public GameEnvSettingDataTable GameEnvSettingDataTable {get; private set;}
		public GameNoiseAudioDataTable GameNoiseAudioDataTable {get; private set;}
		public GamePropDataTable GamePropDataTable {get; private set;}
		public GamePropEditOperationTable GamePropEditOperationTable {get; private set;}
		public GameResDataTable GameResDataTable {get; private set;}
		public GashaponViewConfigTable GashaponViewConfigTable {get; private set;}
		public GroundDataConfigTable GroundDataConfigTable {get; private set;}
		public InitialAvatarTable InitialAvatarTable {get; private set;}
		public InstrumentAniConfigTable InstrumentAniConfigTable {get; private set;}
		public InstrumentConfigTable InstrumentConfigTable {get; private set;}
		public InstrumentToneConfigTable InstrumentToneConfigTable {get; private set;}
		public MapTemplateTable MapTemplateTable {get; private set;}
		public MatDataConfigTable MatDataConfigTable {get; private set;}
		public NetHttpBusinessTable NetHttpBusinessTable {get; private set;}
		public NormalSkyboxDataTable NormalSkyboxDataTable {get; private set;}
		public OtherPublishPriceTable OtherPublishPriceTable {get; private set;}
		public AvatarCommonDataTable PetAvatarCommonDataTable {get; private set;}
		public ClothesTemplateTable PetClothesTemplateTable {get; private set;}
		public EmoUIConfigTable PetEmoUIConfigTable {get; private set;}
		public SkinOrderConfigTable PetSkinOrderConfigTable {get; private set;}
		public UGCClothEditorConfigTable PetUGCClothEditorConfigTable {get; private set;}
		public UgcPartDataTable PetUgcPartDataTable {get; private set;}
		public PgcNameDataTable PgcNameDataTable {get; private set;}
		public PgcNpcConfigTable PgcNpcConfigTable {get; private set;}
		public PgcVehicleConfigTable PgcVehicleConfigTable {get; private set;}
		public PoseEditOperationTable PoseEditOperationTable {get; private set;}
		public PoseModeConfigTable PoseModeConfigTable {get; private set;}
		public PreviewParamsConfigTable PreviewParamsConfigTable {get; private set;}
		public PreviewThemeConfigTable PreviewThemeConfigTable {get; private set;}
		public PropTemplateTable PropTemplateTable {get; private set;}
		public RechargeViewConfigTable RechargeViewConfigTable {get; private set;}
		public RedDotBindConfigTable RedDotBindConfigTable {get; private set;}
		public RedDotUIConfigTable RedDotUIConfigTable {get; private set;}
		public RewardLevelConfigTable RewardLevelConfigTable {get; private set;}
		public SeriesViewConfigTable SeriesViewConfigTable {get; private set;}
		public SkinOrderConfigTable SkinOrderConfigTable {get; private set;}
		public SkinPublishPriceTable SkinPublishPriceTable {get; private set;}
		public SpecialSkinConfigTable SpecialSkinConfigTable {get; private set;}
		public TaskConfigTable TaskConfigTable {get; private set;}
		public UgcAnimBgmConfigTable UgcAnimBgmConfigTable {get; private set;}
		public UGCClothEditorConfigTable UGCClothEditorConfigTable {get; private set;}
		public UGCMaterialTemplateTable UGCMaterialTemplateTable {get; private set;}
		public UgcPartDataTable UgcPartDataTable {get; private set;}
		public UgcScreenGraphicsTable UgcScreenGraphicsTable {get; private set;}
		public UIAvatarNullDataTable UIAvatarNullDataTable {get; private set;}
		public UIPanelTable UIPanelTable {get; private set;}
		public UIWindowTable UIWindowTable {get; private set;}
		public UnityTypesTable UnityTypesTable {get; private set;}
		public VehicleTemplateTable VehicleTemplateTable {get; private set;}
		public VehicleUIConfigTable VehicleUIConfigTable {get; private set;}
		public WaterCubeConfigTable WaterCubeConfigTable {get; private set;}
		public WinConditionTable WinConditionTable {get; private set;}

		private static DataTables s_instance;

		public DataTables()
		{
			s_instance = this;
		}

		public void Load(IEsDataLoader loader)
		{
			_cfgs = new Dictionary<string, EsRowDataTable>();
			ActivityConfigTable = loader.Load("ActivityConfig") as ActivityConfigTable;
			_cfgs.Add("ActivityConfigTable", ActivityConfigTable);
			AnimationConfigTable = loader.Load("AnimationConfig") as AnimationConfigTable;
			_cfgs.Add("AnimationConfigTable", AnimationConfigTable);
			AnniversaryCalendarViewTable = loader.Load("AnniversaryCalendarView") as AnniversaryCalendarViewTable;
			_cfgs.Add("AnniversaryCalendarViewTable", AnniversaryCalendarViewTable);
			AvatarColorDataTable = loader.Load("AvatarColorData") as AvatarColorDataTable;
			_cfgs.Add("AvatarColorDataTable", AvatarColorDataTable);
			AvatarCommonDataTable = loader.Load("AvatarCommonData") as AvatarCommonDataTable;
			_cfgs.Add("AvatarCommonDataTable", AvatarCommonDataTable);
			BundleConfigTable = loader.Load("BundleConfig") as BundleConfigTable;
			_cfgs.Add("BundleConfigTable", BundleConfigTable);
			CabinDefActionConfigTable = loader.Load("CabinDefActionConfig") as CabinDefActionConfigTable;
			_cfgs.Add("CabinDefActionConfigTable", CabinDefActionConfigTable);
			CabinDefCharacterConfigTable = loader.Load("CabinDefCharacterConfig") as CabinDefCharacterConfigTable;
			_cfgs.Add("CabinDefCharacterConfigTable", CabinDefCharacterConfigTable);
			CabinPgcEmoConfigTable = loader.Load("CabinPgcEmoConfig") as CabinPgcEmoConfigTable;
			_cfgs.Add("CabinPgcEmoConfigTable", CabinPgcEmoConfigTable);
			CabinUgcAnimBgmConfigTable = loader.Load("CabinUgcAnimBgmConfig") as CabinUgcAnimBgmConfigTable;
			_cfgs.Add("CabinUgcAnimBgmConfigTable", CabinUgcAnimBgmConfigTable);
			CameraModeResourceTable = loader.Load("CameraModeResource") as CameraModeResourceTable;
			_cfgs.Add("CameraModeResourceTable", CameraModeResourceTable);
			CameraSelfiePoseTable = loader.Load("CameraSelfiePose") as CameraSelfiePoseTable;
			_cfgs.Add("CameraSelfiePoseTable", CameraSelfiePoseTable);
			ClothesTemplateTable = loader.Load("ClothesTemplate") as ClothesTemplateTable;
			_cfgs.Add("ClothesTemplateTable", ClothesTemplateTable);
			ColorDataConfigTable = loader.Load("ColorDataConfig") as ColorDataConfigTable;
			_cfgs.Add("ColorDataConfigTable", ColorDataConfigTable);
			CreatorRewardConfigTable = loader.Load("CreatorRewardConfig") as CreatorRewardConfigTable;
			_cfgs.Add("CreatorRewardConfigTable", CreatorRewardConfigTable);
			DraftBoxCardColorConfigTable = loader.Load("DraftBoxCardColorConfig") as DraftBoxCardColorConfigTable;
			_cfgs.Add("DraftBoxCardColorConfigTable", DraftBoxCardColorConfigTable);
			EmoAniConfigTable = loader.Load("EmoAniConfig") as EmoAniConfigTable;
			_cfgs.Add("EmoAniConfigTable", EmoAniConfigTable);
			EmoUIConfigTable = loader.Load("EmoUIConfig") as EmoUIConfigTable;
			_cfgs.Add("EmoUIConfigTable", EmoUIConfigTable);
			FeatAniConfigTable = loader.Load("FeatAniConfig") as FeatAniConfigTable;
			_cfgs.Add("FeatAniConfigTable", FeatAniConfigTable);
			GameBgAudioDataTable = loader.Load("GameBgAudioData") as GameBgAudioDataTable;
			_cfgs.Add("GameBgAudioDataTable", GameBgAudioDataTable);
			GameEnvSettingDataTable = loader.Load("GameEnvSettingData") as GameEnvSettingDataTable;
			_cfgs.Add("GameEnvSettingDataTable", GameEnvSettingDataTable);
			GameNoiseAudioDataTable = loader.Load("GameNoiseAudioData") as GameNoiseAudioDataTable;
			_cfgs.Add("GameNoiseAudioDataTable", GameNoiseAudioDataTable);
			GamePropDataTable = loader.Load("GamePropData") as GamePropDataTable;
			_cfgs.Add("GamePropDataTable", GamePropDataTable);
			GamePropEditOperationTable = loader.Load("GamePropEditOperation") as GamePropEditOperationTable;
			_cfgs.Add("GamePropEditOperationTable", GamePropEditOperationTable);
			GameResDataTable = loader.Load("GameResData") as GameResDataTable;
			_cfgs.Add("GameResDataTable", GameResDataTable);
			GashaponViewConfigTable = loader.Load("GashaponViewConfig") as GashaponViewConfigTable;
			_cfgs.Add("GashaponViewConfigTable", GashaponViewConfigTable);
			GroundDataConfigTable = loader.Load("GroundDataConfig") as GroundDataConfigTable;
			_cfgs.Add("GroundDataConfigTable", GroundDataConfigTable);
			InitialAvatarTable = loader.Load("InitialAvatar") as InitialAvatarTable;
			_cfgs.Add("InitialAvatarTable", InitialAvatarTable);
			InstrumentAniConfigTable = loader.Load("InstrumentAniConfig") as InstrumentAniConfigTable;
			_cfgs.Add("InstrumentAniConfigTable", InstrumentAniConfigTable);
			InstrumentConfigTable = loader.Load("InstrumentConfig") as InstrumentConfigTable;
			_cfgs.Add("InstrumentConfigTable", InstrumentConfigTable);
			InstrumentToneConfigTable = loader.Load("InstrumentToneConfig") as InstrumentToneConfigTable;
			_cfgs.Add("InstrumentToneConfigTable", InstrumentToneConfigTable);
			MapTemplateTable = loader.Load("MapTemplate") as MapTemplateTable;
			_cfgs.Add("MapTemplateTable", MapTemplateTable);
			MatDataConfigTable = loader.Load("MatDataConfig") as MatDataConfigTable;
			_cfgs.Add("MatDataConfigTable", MatDataConfigTable);
			NetHttpBusinessTable = loader.Load("NetHttpBusiness") as NetHttpBusinessTable;
			_cfgs.Add("NetHttpBusinessTable", NetHttpBusinessTable);
			NormalSkyboxDataTable = loader.Load("NormalSkyboxData") as NormalSkyboxDataTable;
			_cfgs.Add("NormalSkyboxDataTable", NormalSkyboxDataTable);
			OtherPublishPriceTable = loader.Load("OtherPublishPrice") as OtherPublishPriceTable;
			_cfgs.Add("OtherPublishPriceTable", OtherPublishPriceTable);
			PetAvatarCommonDataTable = loader.Load("PetAvatarCommonData") as AvatarCommonDataTable;
			_cfgs.Add("PetAvatarCommonDataTable", PetAvatarCommonDataTable);
			PetClothesTemplateTable = loader.Load("PetClothesTemplate") as ClothesTemplateTable;
			_cfgs.Add("PetClothesTemplateTable", PetClothesTemplateTable);
			PetEmoUIConfigTable = loader.Load("PetEmoUIConfig") as EmoUIConfigTable;
			_cfgs.Add("PetEmoUIConfigTable", PetEmoUIConfigTable);
			PetSkinOrderConfigTable = loader.Load("PetSkinOrderConfig") as SkinOrderConfigTable;
			_cfgs.Add("PetSkinOrderConfigTable", PetSkinOrderConfigTable);
			PetUGCClothEditorConfigTable = loader.Load("PetUGCClothEditorConfig") as UGCClothEditorConfigTable;
			_cfgs.Add("PetUGCClothEditorConfigTable", PetUGCClothEditorConfigTable);
			PetUgcPartDataTable = loader.Load("PetUgcPartData") as UgcPartDataTable;
			_cfgs.Add("PetUgcPartDataTable", PetUgcPartDataTable);
			PgcNameDataTable = loader.Load("PgcNameData") as PgcNameDataTable;
			_cfgs.Add("PgcNameDataTable", PgcNameDataTable);
			PgcNpcConfigTable = loader.Load("PgcNpcConfig") as PgcNpcConfigTable;
			_cfgs.Add("PgcNpcConfigTable", PgcNpcConfigTable);
			PgcVehicleConfigTable = loader.Load("PgcVehicleConfig") as PgcVehicleConfigTable;
			_cfgs.Add("PgcVehicleConfigTable", PgcVehicleConfigTable);
			PoseEditOperationTable = loader.Load("PoseEditOperation") as PoseEditOperationTable;
			_cfgs.Add("PoseEditOperationTable", PoseEditOperationTable);
			PoseModeConfigTable = loader.Load("PoseModeConfig") as PoseModeConfigTable;
			_cfgs.Add("PoseModeConfigTable", PoseModeConfigTable);
			PreviewParamsConfigTable = loader.Load("PreviewParamsConfig") as PreviewParamsConfigTable;
			_cfgs.Add("PreviewParamsConfigTable", PreviewParamsConfigTable);
			PreviewThemeConfigTable = loader.Load("PreviewThemeConfig") as PreviewThemeConfigTable;
			_cfgs.Add("PreviewThemeConfigTable", PreviewThemeConfigTable);
			PropTemplateTable = loader.Load("PropTemplate") as PropTemplateTable;
			_cfgs.Add("PropTemplateTable", PropTemplateTable);
			RechargeViewConfigTable = loader.Load("RechargeViewConfig") as RechargeViewConfigTable;
			_cfgs.Add("RechargeViewConfigTable", RechargeViewConfigTable);
			RedDotBindConfigTable = loader.Load("RedDotBindConfig") as RedDotBindConfigTable;
			_cfgs.Add("RedDotBindConfigTable", RedDotBindConfigTable);
			RedDotUIConfigTable = loader.Load("RedDotUIConfig") as RedDotUIConfigTable;
			_cfgs.Add("RedDotUIConfigTable", RedDotUIConfigTable);
			RewardLevelConfigTable = loader.Load("RewardLevelConfig") as RewardLevelConfigTable;
			_cfgs.Add("RewardLevelConfigTable", RewardLevelConfigTable);
			SeriesViewConfigTable = loader.Load("SeriesViewConfig") as SeriesViewConfigTable;
			_cfgs.Add("SeriesViewConfigTable", SeriesViewConfigTable);
			SkinOrderConfigTable = loader.Load("SkinOrderConfig") as SkinOrderConfigTable;
			_cfgs.Add("SkinOrderConfigTable", SkinOrderConfigTable);
			SkinPublishPriceTable = loader.Load("SkinPublishPrice") as SkinPublishPriceTable;
			_cfgs.Add("SkinPublishPriceTable", SkinPublishPriceTable);
			SpecialSkinConfigTable = loader.Load("SpecialSkinConfig") as SpecialSkinConfigTable;
			_cfgs.Add("SpecialSkinConfigTable", SpecialSkinConfigTable);
			TaskConfigTable = loader.Load("TaskConfig") as TaskConfigTable;
			_cfgs.Add("TaskConfigTable", TaskConfigTable);
			UgcAnimBgmConfigTable = loader.Load("UgcAnimBgmConfig") as UgcAnimBgmConfigTable;
			_cfgs.Add("UgcAnimBgmConfigTable", UgcAnimBgmConfigTable);
			UGCClothEditorConfigTable = loader.Load("UGCClothEditorConfig") as UGCClothEditorConfigTable;
			_cfgs.Add("UGCClothEditorConfigTable", UGCClothEditorConfigTable);
			UGCMaterialTemplateTable = loader.Load("UGCMaterialTemplate") as UGCMaterialTemplateTable;
			_cfgs.Add("UGCMaterialTemplateTable", UGCMaterialTemplateTable);
			UgcPartDataTable = loader.Load("UgcPartData") as UgcPartDataTable;
			_cfgs.Add("UgcPartDataTable", UgcPartDataTable);
			UgcScreenGraphicsTable = loader.Load("UgcScreenGraphics") as UgcScreenGraphicsTable;
			_cfgs.Add("UgcScreenGraphicsTable", UgcScreenGraphicsTable);
			UIAvatarNullDataTable = loader.Load("UIAvatarNullData") as UIAvatarNullDataTable;
			_cfgs.Add("UIAvatarNullDataTable", UIAvatarNullDataTable);
			UIPanelTable = loader.Load("UIPanel") as UIPanelTable;
			_cfgs.Add("UIPanelTable", UIPanelTable);
			UIWindowTable = loader.Load("UIWindow") as UIWindowTable;
			_cfgs.Add("UIWindowTable", UIWindowTable);
			UnityTypesTable = loader.Load("UnityTypes") as UnityTypesTable;
			_cfgs.Add("UnityTypesTable", UnityTypesTable);
			VehicleTemplateTable = loader.Load("VehicleTemplate") as VehicleTemplateTable;
			_cfgs.Add("VehicleTemplateTable", VehicleTemplateTable);
			VehicleUIConfigTable = loader.Load("VehicleUIConfig") as VehicleUIConfigTable;
			_cfgs.Add("VehicleUIConfigTable", VehicleUIConfigTable);
			WaterCubeConfigTable = loader.Load("WaterCubeConfig") as WaterCubeConfigTable;
			_cfgs.Add("WaterCubeConfigTable", WaterCubeConfigTable);
			WinConditionTable = loader.Load("WinCondition") as WinConditionTable;
			_cfgs.Add("WinConditionTable", WinConditionTable);
			PostInit();
		}

		public IEnumerator LoadAsync(IEsDataLoader loader)
		{
			_cfgs = new Dictionary<string, EsRowDataTable>();
			ActivityConfigTable = loader.Load("ActivityConfig") as ActivityConfigTable;
			_cfgs.Add("ActivityConfigTable", ActivityConfigTable);
			AnimationConfigTable = loader.Load("AnimationConfig") as AnimationConfigTable;
			_cfgs.Add("AnimationConfigTable", AnimationConfigTable);
			AnniversaryCalendarViewTable = loader.Load("AnniversaryCalendarView") as AnniversaryCalendarViewTable;
			_cfgs.Add("AnniversaryCalendarViewTable", AnniversaryCalendarViewTable);
			AvatarColorDataTable = loader.Load("AvatarColorData") as AvatarColorDataTable;
			_cfgs.Add("AvatarColorDataTable", AvatarColorDataTable);
			AvatarCommonDataTable = loader.Load("AvatarCommonData") as AvatarCommonDataTable;
			_cfgs.Add("AvatarCommonDataTable", AvatarCommonDataTable);
			yield return null;
			BundleConfigTable = loader.Load("BundleConfig") as BundleConfigTable;
			_cfgs.Add("BundleConfigTable", BundleConfigTable);
			CabinDefActionConfigTable = loader.Load("CabinDefActionConfig") as CabinDefActionConfigTable;
			_cfgs.Add("CabinDefActionConfigTable", CabinDefActionConfigTable);
			CabinDefCharacterConfigTable = loader.Load("CabinDefCharacterConfig") as CabinDefCharacterConfigTable;
			_cfgs.Add("CabinDefCharacterConfigTable", CabinDefCharacterConfigTable);
			CabinPgcEmoConfigTable = loader.Load("CabinPgcEmoConfig") as CabinPgcEmoConfigTable;
			_cfgs.Add("CabinPgcEmoConfigTable", CabinPgcEmoConfigTable);
			CabinUgcAnimBgmConfigTable = loader.Load("CabinUgcAnimBgmConfig") as CabinUgcAnimBgmConfigTable;
			_cfgs.Add("CabinUgcAnimBgmConfigTable", CabinUgcAnimBgmConfigTable);
			yield return null;
			CameraModeResourceTable = loader.Load("CameraModeResource") as CameraModeResourceTable;
			_cfgs.Add("CameraModeResourceTable", CameraModeResourceTable);
			CameraSelfiePoseTable = loader.Load("CameraSelfiePose") as CameraSelfiePoseTable;
			_cfgs.Add("CameraSelfiePoseTable", CameraSelfiePoseTable);
			ClothesTemplateTable = loader.Load("ClothesTemplate") as ClothesTemplateTable;
			_cfgs.Add("ClothesTemplateTable", ClothesTemplateTable);
			ColorDataConfigTable = loader.Load("ColorDataConfig") as ColorDataConfigTable;
			_cfgs.Add("ColorDataConfigTable", ColorDataConfigTable);
			CreatorRewardConfigTable = loader.Load("CreatorRewardConfig") as CreatorRewardConfigTable;
			_cfgs.Add("CreatorRewardConfigTable", CreatorRewardConfigTable);
			yield return null;
			DraftBoxCardColorConfigTable = loader.Load("DraftBoxCardColorConfig") as DraftBoxCardColorConfigTable;
			_cfgs.Add("DraftBoxCardColorConfigTable", DraftBoxCardColorConfigTable);
			EmoAniConfigTable = loader.Load("EmoAniConfig") as EmoAniConfigTable;
			_cfgs.Add("EmoAniConfigTable", EmoAniConfigTable);
			EmoUIConfigTable = loader.Load("EmoUIConfig") as EmoUIConfigTable;
			_cfgs.Add("EmoUIConfigTable", EmoUIConfigTable);
			FeatAniConfigTable = loader.Load("FeatAniConfig") as FeatAniConfigTable;
			_cfgs.Add("FeatAniConfigTable", FeatAniConfigTable);
			GameBgAudioDataTable = loader.Load("GameBgAudioData") as GameBgAudioDataTable;
			_cfgs.Add("GameBgAudioDataTable", GameBgAudioDataTable);
			yield return null;
			GameEnvSettingDataTable = loader.Load("GameEnvSettingData") as GameEnvSettingDataTable;
			_cfgs.Add("GameEnvSettingDataTable", GameEnvSettingDataTable);
			GameNoiseAudioDataTable = loader.Load("GameNoiseAudioData") as GameNoiseAudioDataTable;
			_cfgs.Add("GameNoiseAudioDataTable", GameNoiseAudioDataTable);
			GamePropDataTable = loader.Load("GamePropData") as GamePropDataTable;
			_cfgs.Add("GamePropDataTable", GamePropDataTable);
			GamePropEditOperationTable = loader.Load("GamePropEditOperation") as GamePropEditOperationTable;
			_cfgs.Add("GamePropEditOperationTable", GamePropEditOperationTable);
			GameResDataTable = loader.Load("GameResData") as GameResDataTable;
			_cfgs.Add("GameResDataTable", GameResDataTable);
			yield return null;
			GashaponViewConfigTable = loader.Load("GashaponViewConfig") as GashaponViewConfigTable;
			_cfgs.Add("GashaponViewConfigTable", GashaponViewConfigTable);
			GroundDataConfigTable = loader.Load("GroundDataConfig") as GroundDataConfigTable;
			_cfgs.Add("GroundDataConfigTable", GroundDataConfigTable);
			InitialAvatarTable = loader.Load("InitialAvatar") as InitialAvatarTable;
			_cfgs.Add("InitialAvatarTable", InitialAvatarTable);
			InstrumentAniConfigTable = loader.Load("InstrumentAniConfig") as InstrumentAniConfigTable;
			_cfgs.Add("InstrumentAniConfigTable", InstrumentAniConfigTable);
			InstrumentConfigTable = loader.Load("InstrumentConfig") as InstrumentConfigTable;
			_cfgs.Add("InstrumentConfigTable", InstrumentConfigTable);
			yield return null;
			InstrumentToneConfigTable = loader.Load("InstrumentToneConfig") as InstrumentToneConfigTable;
			_cfgs.Add("InstrumentToneConfigTable", InstrumentToneConfigTable);
			MapTemplateTable = loader.Load("MapTemplate") as MapTemplateTable;
			_cfgs.Add("MapTemplateTable", MapTemplateTable);
			MatDataConfigTable = loader.Load("MatDataConfig") as MatDataConfigTable;
			_cfgs.Add("MatDataConfigTable", MatDataConfigTable);
			NetHttpBusinessTable = loader.Load("NetHttpBusiness") as NetHttpBusinessTable;
			_cfgs.Add("NetHttpBusinessTable", NetHttpBusinessTable);
			NormalSkyboxDataTable = loader.Load("NormalSkyboxData") as NormalSkyboxDataTable;
			_cfgs.Add("NormalSkyboxDataTable", NormalSkyboxDataTable);
			yield return null;
			OtherPublishPriceTable = loader.Load("OtherPublishPrice") as OtherPublishPriceTable;
			_cfgs.Add("OtherPublishPriceTable", OtherPublishPriceTable);
			PetAvatarCommonDataTable = loader.Load("PetAvatarCommonData") as AvatarCommonDataTable;
			_cfgs.Add("PetAvatarCommonDataTable", PetAvatarCommonDataTable);
			PetClothesTemplateTable = loader.Load("PetClothesTemplate") as ClothesTemplateTable;
			_cfgs.Add("PetClothesTemplateTable", PetClothesTemplateTable);
			PetEmoUIConfigTable = loader.Load("PetEmoUIConfig") as EmoUIConfigTable;
			_cfgs.Add("PetEmoUIConfigTable", PetEmoUIConfigTable);
			PetSkinOrderConfigTable = loader.Load("PetSkinOrderConfig") as SkinOrderConfigTable;
			_cfgs.Add("PetSkinOrderConfigTable", PetSkinOrderConfigTable);
			yield return null;
			PetUGCClothEditorConfigTable = loader.Load("PetUGCClothEditorConfig") as UGCClothEditorConfigTable;
			_cfgs.Add("PetUGCClothEditorConfigTable", PetUGCClothEditorConfigTable);
			PetUgcPartDataTable = loader.Load("PetUgcPartData") as UgcPartDataTable;
			_cfgs.Add("PetUgcPartDataTable", PetUgcPartDataTable);
			PgcNameDataTable = loader.Load("PgcNameData") as PgcNameDataTable;
			_cfgs.Add("PgcNameDataTable", PgcNameDataTable);
			PgcNpcConfigTable = loader.Load("PgcNpcConfig") as PgcNpcConfigTable;
			_cfgs.Add("PgcNpcConfigTable", PgcNpcConfigTable);
			PgcVehicleConfigTable = loader.Load("PgcVehicleConfig") as PgcVehicleConfigTable;
			_cfgs.Add("PgcVehicleConfigTable", PgcVehicleConfigTable);
			yield return null;
			PoseEditOperationTable = loader.Load("PoseEditOperation") as PoseEditOperationTable;
			_cfgs.Add("PoseEditOperationTable", PoseEditOperationTable);
			PoseModeConfigTable = loader.Load("PoseModeConfig") as PoseModeConfigTable;
			_cfgs.Add("PoseModeConfigTable", PoseModeConfigTable);
			PreviewParamsConfigTable = loader.Load("PreviewParamsConfig") as PreviewParamsConfigTable;
			_cfgs.Add("PreviewParamsConfigTable", PreviewParamsConfigTable);
			PreviewThemeConfigTable = loader.Load("PreviewThemeConfig") as PreviewThemeConfigTable;
			_cfgs.Add("PreviewThemeConfigTable", PreviewThemeConfigTable);
			PropTemplateTable = loader.Load("PropTemplate") as PropTemplateTable;
			_cfgs.Add("PropTemplateTable", PropTemplateTable);
			yield return null;
			RechargeViewConfigTable = loader.Load("RechargeViewConfig") as RechargeViewConfigTable;
			_cfgs.Add("RechargeViewConfigTable", RechargeViewConfigTable);
			RedDotBindConfigTable = loader.Load("RedDotBindConfig") as RedDotBindConfigTable;
			_cfgs.Add("RedDotBindConfigTable", RedDotBindConfigTable);
			RedDotUIConfigTable = loader.Load("RedDotUIConfig") as RedDotUIConfigTable;
			_cfgs.Add("RedDotUIConfigTable", RedDotUIConfigTable);
			RewardLevelConfigTable = loader.Load("RewardLevelConfig") as RewardLevelConfigTable;
			_cfgs.Add("RewardLevelConfigTable", RewardLevelConfigTable);
			SeriesViewConfigTable = loader.Load("SeriesViewConfig") as SeriesViewConfigTable;
			_cfgs.Add("SeriesViewConfigTable", SeriesViewConfigTable);
			yield return null;
			SkinOrderConfigTable = loader.Load("SkinOrderConfig") as SkinOrderConfigTable;
			_cfgs.Add("SkinOrderConfigTable", SkinOrderConfigTable);
			SkinPublishPriceTable = loader.Load("SkinPublishPrice") as SkinPublishPriceTable;
			_cfgs.Add("SkinPublishPriceTable", SkinPublishPriceTable);
			SpecialSkinConfigTable = loader.Load("SpecialSkinConfig") as SpecialSkinConfigTable;
			_cfgs.Add("SpecialSkinConfigTable", SpecialSkinConfigTable);
			TaskConfigTable = loader.Load("TaskConfig") as TaskConfigTable;
			_cfgs.Add("TaskConfigTable", TaskConfigTable);
			UgcAnimBgmConfigTable = loader.Load("UgcAnimBgmConfig") as UgcAnimBgmConfigTable;
			_cfgs.Add("UgcAnimBgmConfigTable", UgcAnimBgmConfigTable);
			yield return null;
			UGCClothEditorConfigTable = loader.Load("UGCClothEditorConfig") as UGCClothEditorConfigTable;
			_cfgs.Add("UGCClothEditorConfigTable", UGCClothEditorConfigTable);
			UGCMaterialTemplateTable = loader.Load("UGCMaterialTemplate") as UGCMaterialTemplateTable;
			_cfgs.Add("UGCMaterialTemplateTable", UGCMaterialTemplateTable);
			UgcPartDataTable = loader.Load("UgcPartData") as UgcPartDataTable;
			_cfgs.Add("UgcPartDataTable", UgcPartDataTable);
			UgcScreenGraphicsTable = loader.Load("UgcScreenGraphics") as UgcScreenGraphicsTable;
			_cfgs.Add("UgcScreenGraphicsTable", UgcScreenGraphicsTable);
			UIAvatarNullDataTable = loader.Load("UIAvatarNullData") as UIAvatarNullDataTable;
			_cfgs.Add("UIAvatarNullDataTable", UIAvatarNullDataTable);
			yield return null;
			UIPanelTable = loader.Load("UIPanel") as UIPanelTable;
			_cfgs.Add("UIPanelTable", UIPanelTable);
			UIWindowTable = loader.Load("UIWindow") as UIWindowTable;
			_cfgs.Add("UIWindowTable", UIWindowTable);
			UnityTypesTable = loader.Load("UnityTypes") as UnityTypesTable;
			_cfgs.Add("UnityTypesTable", UnityTypesTable);
			VehicleTemplateTable = loader.Load("VehicleTemplate") as VehicleTemplateTable;
			_cfgs.Add("VehicleTemplateTable", VehicleTemplateTable);
			VehicleUIConfigTable = loader.Load("VehicleUIConfig") as VehicleUIConfigTable;
			_cfgs.Add("VehicleUIConfigTable", VehicleUIConfigTable);
			yield return null;
			WaterCubeConfigTable = loader.Load("WaterCubeConfig") as WaterCubeConfigTable;
			_cfgs.Add("WaterCubeConfigTable", WaterCubeConfigTable);
			WinConditionTable = loader.Load("WinCondition") as WinConditionTable;
			_cfgs.Add("WinConditionTable", WinConditionTable);
			PostInit();
		}

		partial void PostInit();


		public static ActivityConfig GetActivityConfig(int id)
		{
			return s_instance.ActivityConfigTable.Get(id);
		}

		public static List<ActivityConfig> GetActivityConfigList()
		{
			return s_instance.ActivityConfigTable.DataList;
		}

		public static AnimationConfig GetAnimationConfig(string id)
		{
			return s_instance.AnimationConfigTable.Get(id);
		}

		public static List<AnimationConfig> GetAnimationConfigList()
		{
			return s_instance.AnimationConfigTable.DataList;
		}

		public static AnniversaryCalendarView GetAnniversaryCalendarView(int id)
		{
			return s_instance.AnniversaryCalendarViewTable.Get(id);
		}

		public static List<AnniversaryCalendarView> GetAnniversaryCalendarViewList()
		{
			return s_instance.AnniversaryCalendarViewTable.DataList;
		}

		public static AvatarColorData GetAvatarColorData(string id)
		{
			return s_instance.AvatarColorDataTable.Get(id);
		}

		public static List<AvatarColorData> GetAvatarColorDataList()
		{
			return s_instance.AvatarColorDataTable.DataList;
		}

		public static AvatarCommonData GetAvatarCommonData(string id)
		{
			return s_instance.AvatarCommonDataTable.Get(id);
		}

		public static List<AvatarCommonData> GetAvatarCommonDataList()
		{
			return s_instance.AvatarCommonDataTable.DataList;
		}

		public static BundleConfig GetBundleConfig(string id)
		{
			return s_instance.BundleConfigTable.Get(id);
		}

		public static List<BundleConfig> GetBundleConfigList()
		{
			return s_instance.BundleConfigTable.DataList;
		}

		public static CabinDefActionConfig GetCabinDefActionConfig(string id)
		{
			return s_instance.CabinDefActionConfigTable.Get(id);
		}

		public static List<CabinDefActionConfig> GetCabinDefActionConfigList()
		{
			return s_instance.CabinDefActionConfigTable.DataList;
		}

		public static CabinDefCharacterConfig GetCabinDefCharacterConfig(string id)
		{
			return s_instance.CabinDefCharacterConfigTable.Get(id);
		}

		public static List<CabinDefCharacterConfig> GetCabinDefCharacterConfigList()
		{
			return s_instance.CabinDefCharacterConfigTable.DataList;
		}

		public static CabinPgcEmoConfig GetCabinPgcEmoConfig(int id)
		{
			return s_instance.CabinPgcEmoConfigTable.Get(id);
		}

		public static List<CabinPgcEmoConfig> GetCabinPgcEmoConfigList()
		{
			return s_instance.CabinPgcEmoConfigTable.DataList;
		}

		public static CabinUgcAnimBgmConfig GetCabinUgcAnimBgmConfig(string id)
		{
			return s_instance.CabinUgcAnimBgmConfigTable.Get(id);
		}

		public static List<CabinUgcAnimBgmConfig> GetCabinUgcAnimBgmConfigList()
		{
			return s_instance.CabinUgcAnimBgmConfigTable.DataList;
		}

		public static CameraModeResource GetCameraModeResource(int id)
		{
			return s_instance.CameraModeResourceTable.Get(id);
		}

		public static List<CameraModeResource> GetCameraModeResourceList()
		{
			return s_instance.CameraModeResourceTable.DataList;
		}

		public static CameraSelfiePose GetCameraSelfiePose(string id)
		{
			return s_instance.CameraSelfiePoseTable.Get(id);
		}

		public static List<CameraSelfiePose> GetCameraSelfiePoseList()
		{
			return s_instance.CameraSelfiePoseTable.DataList;
		}

		public static ClothesTemplate GetClothesTemplate(string id)
		{
			return s_instance.ClothesTemplateTable.Get(id);
		}

		public static List<ClothesTemplate> GetClothesTemplateList()
		{
			return s_instance.ClothesTemplateTable.DataList;
		}

		public static ColorDataConfig GetColorDataConfig(int id)
		{
			return s_instance.ColorDataConfigTable.Get(id);
		}

		public static List<ColorDataConfig> GetColorDataConfigList()
		{
			return s_instance.ColorDataConfigTable.DataList;
		}

		public static CreatorRewardConfig GetCreatorRewardConfig(int id)
		{
			return s_instance.CreatorRewardConfigTable.Get(id);
		}

		public static List<CreatorRewardConfig> GetCreatorRewardConfigList()
		{
			return s_instance.CreatorRewardConfigTable.DataList;
		}

		public static DraftBoxCardColorConfig GetDraftBoxCardColorConfig(int id)
		{
			return s_instance.DraftBoxCardColorConfigTable.Get(id);
		}

		public static List<DraftBoxCardColorConfig> GetDraftBoxCardColorConfigList()
		{
			return s_instance.DraftBoxCardColorConfigTable.DataList;
		}

		public static EmoAniConfig GetEmoAniConfig(int id)
		{
			return s_instance.EmoAniConfigTable.Get(id);
		}

		public static List<EmoAniConfig> GetEmoAniConfigList()
		{
			return s_instance.EmoAniConfigTable.DataList;
		}

		public static EmoUIConfig GetEmoUIConfig(string id)
		{
			return s_instance.EmoUIConfigTable.Get(id);
		}

		public static List<EmoUIConfig> GetEmoUIConfigList()
		{
			return s_instance.EmoUIConfigTable.DataList;
		}

		public static FeatAniConfig GetFeatAniConfig(int id)
		{
			return s_instance.FeatAniConfigTable.Get(id);
		}

		public static List<FeatAniConfig> GetFeatAniConfigList()
		{
			return s_instance.FeatAniConfigTable.DataList;
		}

		public static GameBgAudioData GetGameBgAudioData(string id)
		{
			return s_instance.GameBgAudioDataTable.Get(id);
		}

		public static List<GameBgAudioData> GetGameBgAudioDataList()
		{
			return s_instance.GameBgAudioDataTable.DataList;
		}

		public static GameEnvSettingData GetGameEnvSettingData(string id)
		{
			return s_instance.GameEnvSettingDataTable.Get(id);
		}

		public static List<GameEnvSettingData> GetGameEnvSettingDataList()
		{
			return s_instance.GameEnvSettingDataTable.DataList;
		}

		public static GameNoiseAudioData GetGameNoiseAudioData(string id)
		{
			return s_instance.GameNoiseAudioDataTable.Get(id);
		}

		public static List<GameNoiseAudioData> GetGameNoiseAudioDataList()
		{
			return s_instance.GameNoiseAudioDataTable.DataList;
		}

		public static GamePropData GetGamePropData(string id)
		{
			return s_instance.GamePropDataTable.Get(id);
		}

		public static List<GamePropData> GetGamePropDataList()
		{
			return s_instance.GamePropDataTable.DataList;
		}

		public static GamePropEditOperation GetGamePropEditOperation(int id)
		{
			return s_instance.GamePropEditOperationTable.Get(id);
		}

		public static List<GamePropEditOperation> GetGamePropEditOperationList()
		{
			return s_instance.GamePropEditOperationTable.DataList;
		}

		public static GameResData GetGameResData(string id)
		{
			return s_instance.GameResDataTable.Get(id);
		}

		public static List<GameResData> GetGameResDataList()
		{
			return s_instance.GameResDataTable.DataList;
		}

		public static GashaponViewConfig GetGashaponViewConfig(int id)
		{
			return s_instance.GashaponViewConfigTable.Get(id);
		}

		public static List<GashaponViewConfig> GetGashaponViewConfigList()
		{
			return s_instance.GashaponViewConfigTable.DataList;
		}

		public static GroundDataConfig GetGroundDataConfig(int id)
		{
			return s_instance.GroundDataConfigTable.Get(id);
		}

		public static List<GroundDataConfig> GetGroundDataConfigList()
		{
			return s_instance.GroundDataConfigTable.DataList;
		}

		public static InitialAvatar GetInitialAvatar(string id)
		{
			return s_instance.InitialAvatarTable.Get(id);
		}

		public static List<InitialAvatar> GetInitialAvatarList()
		{
			return s_instance.InitialAvatarTable.DataList;
		}

		public static InstrumentAniConfig GetInstrumentAniConfig(int id)
		{
			return s_instance.InstrumentAniConfigTable.Get(id);
		}

		public static List<InstrumentAniConfig> GetInstrumentAniConfigList()
		{
			return s_instance.InstrumentAniConfigTable.DataList;
		}

		public static InstrumentConfig GetInstrumentConfig(string id)
		{
			return s_instance.InstrumentConfigTable.Get(id);
		}

		public static List<InstrumentConfig> GetInstrumentConfigList()
		{
			return s_instance.InstrumentConfigTable.DataList;
		}

		public static InstrumentToneConfig GetInstrumentToneConfig(string id)
		{
			return s_instance.InstrumentToneConfigTable.Get(id);
		}

		public static List<InstrumentToneConfig> GetInstrumentToneConfigList()
		{
			return s_instance.InstrumentToneConfigTable.DataList;
		}

		public static MapTemplate GetMapTemplate(string id)
		{
			return s_instance.MapTemplateTable.Get(id);
		}

		public static List<MapTemplate> GetMapTemplateList()
		{
			return s_instance.MapTemplateTable.DataList;
		}

		public static MatDataConfig GetMatDataConfig(int id)
		{
			return s_instance.MatDataConfigTable.Get(id);
		}

		public static List<MatDataConfig> GetMatDataConfigList()
		{
			return s_instance.MatDataConfigTable.DataList;
		}

		public static NetHttpBusiness GetNetHttpBusiness(string id)
		{
			return s_instance.NetHttpBusinessTable.Get(id);
		}

		public static List<NetHttpBusiness> GetNetHttpBusinessList()
		{
			return s_instance.NetHttpBusinessTable.DataList;
		}

		public static NormalSkyboxData GetNormalSkyboxData(string id)
		{
			return s_instance.NormalSkyboxDataTable.Get(id);
		}

		public static List<NormalSkyboxData> GetNormalSkyboxDataList()
		{
			return s_instance.NormalSkyboxDataTable.DataList;
		}

		public static OtherPublishPrice GetOtherPublishPrice(int id)
		{
			return s_instance.OtherPublishPriceTable.Get(id);
		}

		public static List<OtherPublishPrice> GetOtherPublishPriceList()
		{
			return s_instance.OtherPublishPriceTable.DataList;
		}

		public static AvatarCommonData GetPetAvatarCommonData(string id)
		{
			return s_instance.PetAvatarCommonDataTable.Get(id);
		}

		public static List<AvatarCommonData> GetPetAvatarCommonDataList()
		{
			return s_instance.PetAvatarCommonDataTable.DataList;
		}

		public static ClothesTemplate GetPetClothesTemplate(string id)
		{
			return s_instance.PetClothesTemplateTable.Get(id);
		}

		public static List<ClothesTemplate> GetPetClothesTemplateList()
		{
			return s_instance.PetClothesTemplateTable.DataList;
		}

		public static EmoUIConfig GetPetEmoUIConfig(string id)
		{
			return s_instance.PetEmoUIConfigTable.Get(id);
		}

		public static List<EmoUIConfig> GetPetEmoUIConfigList()
		{
			return s_instance.PetEmoUIConfigTable.DataList;
		}

		public static SkinOrderConfig GetPetSkinOrderConfig(string id)
		{
			return s_instance.PetSkinOrderConfigTable.Get(id);
		}

		public static List<SkinOrderConfig> GetPetSkinOrderConfigList()
		{
			return s_instance.PetSkinOrderConfigTable.DataList;
		}

		public static UGCClothEditorConfig GetPetUGCClothEditorConfig(string id)
		{
			return s_instance.PetUGCClothEditorConfigTable.Get(id);
		}

		public static List<UGCClothEditorConfig> GetPetUGCClothEditorConfigList()
		{
			return s_instance.PetUGCClothEditorConfigTable.DataList;
		}

		public static UgcPartData GetPetUgcPartData(string id)
		{
			return s_instance.PetUgcPartDataTable.Get(id);
		}

		public static List<UgcPartData> GetPetUgcPartDataList()
		{
			return s_instance.PetUgcPartDataTable.DataList;
		}

		public static PgcNameData GetPgcNameData(string id)
		{
			return s_instance.PgcNameDataTable.Get(id);
		}

		public static List<PgcNameData> GetPgcNameDataList()
		{
			return s_instance.PgcNameDataTable.DataList;
		}

		public static PgcNpcConfig GetPgcNpcConfig(int id)
		{
			return s_instance.PgcNpcConfigTable.Get(id);
		}

		public static List<PgcNpcConfig> GetPgcNpcConfigList()
		{
			return s_instance.PgcNpcConfigTable.DataList;
		}

		public static PgcVehicleConfig GetPgcVehicleConfig(int id)
		{
			return s_instance.PgcVehicleConfigTable.Get(id);
		}

		public static List<PgcVehicleConfig> GetPgcVehicleConfigList()
		{
			return s_instance.PgcVehicleConfigTable.DataList;
		}

		public static PoseEditOperation GetPoseEditOperation(string id)
		{
			return s_instance.PoseEditOperationTable.Get(id);
		}

		public static List<PoseEditOperation> GetPoseEditOperationList()
		{
			return s_instance.PoseEditOperationTable.DataList;
		}

		public static PoseModeConfig GetPoseModeConfig(int id)
		{
			return s_instance.PoseModeConfigTable.Get(id);
		}

		public static List<PoseModeConfig> GetPoseModeConfigList()
		{
			return s_instance.PoseModeConfigTable.DataList;
		}

		public static PreviewParamsConfig GetPreviewParamsConfig(int id)
		{
			return s_instance.PreviewParamsConfigTable.Get(id);
		}

		public static List<PreviewParamsConfig> GetPreviewParamsConfigList()
		{
			return s_instance.PreviewParamsConfigTable.DataList;
		}

		public static PreviewThemeConfig GetPreviewThemeConfig(string id)
		{
			return s_instance.PreviewThemeConfigTable.Get(id);
		}

		public static List<PreviewThemeConfig> GetPreviewThemeConfigList()
		{
			return s_instance.PreviewThemeConfigTable.DataList;
		}

		public static PropTemplate GetPropTemplate(string id)
		{
			return s_instance.PropTemplateTable.Get(id);
		}

		public static List<PropTemplate> GetPropTemplateList()
		{
			return s_instance.PropTemplateTable.DataList;
		}

		public static RechargeViewConfig GetRechargeViewConfig(int id)
		{
			return s_instance.RechargeViewConfigTable.Get(id);
		}

		public static List<RechargeViewConfig> GetRechargeViewConfigList()
		{
			return s_instance.RechargeViewConfigTable.DataList;
		}

		public static RedDotBindConfig GetRedDotBindConfig(int id)
		{
			return s_instance.RedDotBindConfigTable.Get(id);
		}

		public static List<RedDotBindConfig> GetRedDotBindConfigList()
		{
			return s_instance.RedDotBindConfigTable.DataList;
		}

		public static RedDotUIConfig GetRedDotUIConfig(int id)
		{
			return s_instance.RedDotUIConfigTable.Get(id);
		}

		public static List<RedDotUIConfig> GetRedDotUIConfigList()
		{
			return s_instance.RedDotUIConfigTable.DataList;
		}

		public static RewardLevelConfig GetRewardLevelConfig(int id)
		{
			return s_instance.RewardLevelConfigTable.Get(id);
		}

		public static List<RewardLevelConfig> GetRewardLevelConfigList()
		{
			return s_instance.RewardLevelConfigTable.DataList;
		}

		public static SeriesViewConfig GetSeriesViewConfig(int id)
		{
			return s_instance.SeriesViewConfigTable.Get(id);
		}

		public static List<SeriesViewConfig> GetSeriesViewConfigList()
		{
			return s_instance.SeriesViewConfigTable.DataList;
		}

		public static SkinOrderConfig GetSkinOrderConfig(string id)
		{
			return s_instance.SkinOrderConfigTable.Get(id);
		}

		public static List<SkinOrderConfig> GetSkinOrderConfigList()
		{
			return s_instance.SkinOrderConfigTable.DataList;
		}

		public static SkinPublishPrice GetSkinPublishPrice(int id)
		{
			return s_instance.SkinPublishPriceTable.Get(id);
		}

		public static List<SkinPublishPrice> GetSkinPublishPriceList()
		{
			return s_instance.SkinPublishPriceTable.DataList;
		}

		public static SpecialSkinConfig GetSpecialSkinConfig(string id)
		{
			return s_instance.SpecialSkinConfigTable.Get(id);
		}

		public static List<SpecialSkinConfig> GetSpecialSkinConfigList()
		{
			return s_instance.SpecialSkinConfigTable.DataList;
		}

		public static TaskConfig GetTaskConfig(int id)
		{
			return s_instance.TaskConfigTable.Get(id);
		}

		public static List<TaskConfig> GetTaskConfigList()
		{
			return s_instance.TaskConfigTable.DataList;
		}

		public static UgcAnimBgmConfig GetUgcAnimBgmConfig(string id)
		{
			return s_instance.UgcAnimBgmConfigTable.Get(id);
		}

		public static List<UgcAnimBgmConfig> GetUgcAnimBgmConfigList()
		{
			return s_instance.UgcAnimBgmConfigTable.DataList;
		}

		public static UGCClothEditorConfig GetUGCClothEditorConfig(string id)
		{
			return s_instance.UGCClothEditorConfigTable.Get(id);
		}

		public static List<UGCClothEditorConfig> GetUGCClothEditorConfigList()
		{
			return s_instance.UGCClothEditorConfigTable.DataList;
		}

		public static UGCMaterialTemplate GetUGCMaterialTemplate(string id)
		{
			return s_instance.UGCMaterialTemplateTable.Get(id);
		}

		public static List<UGCMaterialTemplate> GetUGCMaterialTemplateList()
		{
			return s_instance.UGCMaterialTemplateTable.DataList;
		}

		public static UgcPartData GetUgcPartData(string id)
		{
			return s_instance.UgcPartDataTable.Get(id);
		}

		public static List<UgcPartData> GetUgcPartDataList()
		{
			return s_instance.UgcPartDataTable.DataList;
		}

		public static UgcScreenGraphics GetUgcScreenGraphics(string id)
		{
			return s_instance.UgcScreenGraphicsTable.Get(id);
		}

		public static List<UgcScreenGraphics> GetUgcScreenGraphicsList()
		{
			return s_instance.UgcScreenGraphicsTable.DataList;
		}

		public static UIAvatarNullData GetUIAvatarNullData(string id)
		{
			return s_instance.UIAvatarNullDataTable.Get(id);
		}

		public static List<UIAvatarNullData> GetUIAvatarNullDataList()
		{
			return s_instance.UIAvatarNullDataTable.DataList;
		}

		public static UIPanel GetUIPanel(int id)
		{
			return s_instance.UIPanelTable.Get(id);
		}

		public static List<UIPanel> GetUIPanelList()
		{
			return s_instance.UIPanelTable.DataList;
		}

		public static UIWindow GetUIWindow(int id)
		{
			return s_instance.UIWindowTable.Get(id);
		}

		public static List<UIWindow> GetUIWindowList()
		{
			return s_instance.UIWindowTable.DataList;
		}

		public static UnityTypes GetUnityTypes(int id)
		{
			return s_instance.UnityTypesTable.Get(id);
		}

		public static List<UnityTypes> GetUnityTypesList()
		{
			return s_instance.UnityTypesTable.DataList;
		}

		public static VehicleTemplate GetVehicleTemplate(string id)
		{
			return s_instance.VehicleTemplateTable.Get(id);
		}

		public static List<VehicleTemplate> GetVehicleTemplateList()
		{
			return s_instance.VehicleTemplateTable.DataList;
		}

		public static VehicleUIConfig GetVehicleUIConfig(string id)
		{
			return s_instance.VehicleUIConfigTable.Get(id);
		}

		public static List<VehicleUIConfig> GetVehicleUIConfigList()
		{
			return s_instance.VehicleUIConfigTable.DataList;
		}

		public static WaterCubeConfig GetWaterCubeConfig(int id)
		{
			return s_instance.WaterCubeConfigTable.Get(id);
		}

		public static List<WaterCubeConfig> GetWaterCubeConfigList()
		{
			return s_instance.WaterCubeConfigTable.DataList;
		}

		public static WinCondition GetWinCondition(int id)
		{
			return s_instance.WinConditionTable.Get(id);
		}

		public static List<WinCondition> GetWinConditionList()
		{
			return s_instance.WinConditionTable.DataList;
		}

	}
}
