//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	public sealed partial class FeatAniConfigTable : EsRowDataTable
	{
		[SerializeField]
		private List<FeatAniConfig> _dataList = new List<FeatAniConfig>();

		private Dictionary<int, FeatAniConfig> _dataMap;
		public Dictionary<int, FeatAniConfig> DataMap => _dataMap;
		public List<FeatAniConfig> DataList => _dataList;

		public FeatAniConfig Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
		public FeatAniConfig this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

		protected override void OnDeserialized()
		{
			_dataMap = new Dictionary<int, FeatAniConfig>(_dataList.Count);
			foreach (var data in _dataList)
			{
				_dataMap.Add(data.id, data);
				(data as ISerializationCallbackReceiver).OnAfterDeserialize();
			}
			PostInit();
		}

		partial void PostInit();
	}
}
