//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class FeatAniConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _id;
		public int id => _id;

		[SerializeField]
		private string _name;
		public string name => _name;

		[SerializeField]
		private int _StateID;
		public int StateID => _StateID;

		[SerializeField]
		private string _aniType;
		public string aniType => _aniType;

		[SerializeField]
		private string _bodyPath;
		public string bodyPath => _bodyPath;

		[SerializeField]
		private string _facePath;
		public string facePath => _facePath;

		[SerializeField]
		private float _faceDelayTime;
		public float faceDelayTime => _faceDelayTime;

		[SerializeField]
		private float _faceEndTime;
		public float faceEndTime => _faceEndTime;

		[SerializeField]
		private List<string> _effectPath;
		public List<string> effectPath => _effectPath;

		[SerializeField]
		private int _randomCount;
		public int randomCount => _randomCount;

		[SerializeField]
		private List<int> _bandId;
		public List<int> bandId => _bandId;

		[SerializeField]
		private List<int> _bandNode;
		public List<int> bandNode => _bandNode;

		[SerializeField]
		private List<UnityEngine.Vector3> _r;
		public List<UnityEngine.Vector3> r => _r;

		[SerializeField]
		private List<UnityEngine.Vector3> _s;
		public List<UnityEngine.Vector3> s => _s;

		[SerializeField]
		private List<UnityEngine.Vector3> _p;
		public List<UnityEngine.Vector3> p => _p;

		[SerializeField]
		private string _effectAnimName;
		public string effectAnimName => _effectAnimName;

		[SerializeField]
		private string _soundName;
		public string soundName => _soundName;


		public FeatAniConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _id);
			EsParser.TryParse(cells[column++], out _name);
			EsParser.TryParse(cells[column++], out _StateID);
			EsParser.TryParse(cells[column++], out _aniType);
			EsParser.TryParse(cells[column++], out _bodyPath);
			EsParser.TryParse(cells[column++], out _facePath);
			EsParser.TryParse(cells[column++], out _faceDelayTime);
			EsParser.TryParse(cells[column++], out _faceEndTime);
			string[] _effectPath_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_effectPath = new List<string>(_effectPath_parts_.Length);
			for(int i = 0; i < _effectPath_parts_.Length; i++)
			{
				EsParser.TryParse(_effectPath_parts_[i], out string _temp_);
				_effectPath.Add(_temp_);
			}
			EsParser.TryParse(cells[column++], out _randomCount);
			string[] _bandId_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_bandId = new List<int>(_bandId_parts_.Length);
			for(int i = 0; i < _bandId_parts_.Length; i++)
			{
				EsParser.TryParse(_bandId_parts_[i], out int _temp_);
				_bandId.Add(_temp_);
			}
			string[] _bandNode_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_bandNode = new List<int>(_bandNode_parts_.Length);
			for(int i = 0; i < _bandNode_parts_.Length; i++)
			{
				EsParser.TryParse(_bandNode_parts_[i], out int _temp_);
				_bandNode.Add(_temp_);
			}
			string[] _r_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_r = new List<UnityEngine.Vector3>(_r_parts_.Length);
			for(int i = 0; i < _r_parts_.Length; i++)
			{
				var _temp_ = new UnityEngine.Vector3();
				UnityTypesParse.Parse(ref _temp_, _r_parts_[i]);
				_r.Add(_temp_);
			}
			string[] _s_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_s = new List<UnityEngine.Vector3>(_s_parts_.Length);
			for(int i = 0; i < _s_parts_.Length; i++)
			{
				var _temp_ = new UnityEngine.Vector3();
				UnityTypesParse.Parse(ref _temp_, _s_parts_[i]);
				_s.Add(_temp_);
			}
			string[] _p_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_p = new List<UnityEngine.Vector3>(_p_parts_.Length);
			for(int i = 0; i < _p_parts_.Length; i++)
			{
				var _temp_ = new UnityEngine.Vector3();
				UnityTypesParse.Parse(ref _temp_, _p_parts_[i]);
				_p.Add(_temp_);
			}
			EsParser.TryParse(cells[column++], out _effectAnimName);
			EsParser.TryParse(cells[column++], out _soundName);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}