//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class GamePropEditOperation : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _Id;
		public int Id => _Id;

		[SerializeField]
		private int _Move;
		public int Move => _Move;

		[SerializeField]
		private int _Rotate;
		public int Rotate => _Rotate;

		[SerializeField]
		private int _Scale;
		public int Scale => _Scale;

		[SerializeField]
		private int _Copy;
		public int Copy => _Copy;

		[SerializeField]
		private int _Lock;
		public int Lock => _Lock;

		[SerializeField]
		private int _Hide;
		public int Hide => _Hide;

		[SerializeField]
		private int _PublishProp;
		public int PublishProp => _PublishProp;

		[SerializeField]
		private int _CanDelete;
		public int CanDelete => _CanDelete;

		[SerializeField]
		private int _CanCombine;
		public int CanCombine => _CanCombine;

		[SerializeField]
		private int _Animation;
		public int Animation => _Animation;

		[SerializeField]
		private int _Movement;
		public int Movement => _Movement;

		[SerializeField]
		private int _Visibility;
		public int Visibility => _Visibility;

		[SerializeField]
		private int _Transaction;
		public int Transaction => _Transaction;

		[SerializeField]
		private int _Interaction;
		public int Interaction => _Interaction;

		[SerializeField]
		private int _Collision;
		public int Collision => _Collision;

		[SerializeField]
		private int _Rendering;
		public int Rendering => _Rendering;


		public GamePropEditOperation()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _Id);
			EsParser.TryParse(cells[column++], out _Move);
			EsParser.TryParse(cells[column++], out _Rotate);
			EsParser.TryParse(cells[column++], out _Scale);
			EsParser.TryParse(cells[column++], out _Copy);
			EsParser.TryParse(cells[column++], out _Lock);
			EsParser.TryParse(cells[column++], out _Hide);
			EsParser.TryParse(cells[column++], out _PublishProp);
			EsParser.TryParse(cells[column++], out _CanDelete);
			EsParser.TryParse(cells[column++], out _CanCombine);
			EsParser.TryParse(cells[column++], out _Animation);
			EsParser.TryParse(cells[column++], out _Movement);
			EsParser.TryParse(cells[column++], out _Visibility);
			EsParser.TryParse(cells[column++], out _Transaction);
			EsParser.TryParse(cells[column++], out _Interaction);
			EsParser.TryParse(cells[column++], out _Collision);
			EsParser.TryParse(cells[column++], out _Rendering);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}