//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	public sealed partial class GamePropDataTable : EsRowDataTable
	{
		[SerializeField]
		private List<GamePropData> _dataList = new List<GamePropData>();

		private Dictionary<string, GamePropData> _dataMap;
		public Dictionary<string, GamePropData> DataMap => _dataMap;
		public List<GamePropData> DataList => _dataList;

		public GamePropData Get(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
		public GamePropData this[string key] => _dataMap.TryGetValue(key, out var v) ? v : null;

		protected override void OnDeserialized()
		{
			_dataMap = new Dictionary<string, GamePropData>(_dataList.Count);
			foreach (var data in _dataList)
			{
				_dataMap.Add(data.Id, data);
				(data as ISerializationCallbackReceiver).OnAfterDeserialize();
			}
			PostInit();
		}

		partial void PostInit();
	}
}
