//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class GamePropData : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _Id;
		public string Id => _Id;

		[SerializeField]
		private int _Order;
		public int Order => _Order;

		[SerializeField]
		private int _ModelType;
		public int ModelType => _ModelType;

		[SerializeField]
		private int _BannerType;
		public int BannerType => _BannerType;

		[SerializeField]
		private int _HandleType;
		public int HandleType => _HandleType;

		[SerializeField]
		private string _IconName;
		public string IconName => _IconName;

		[SerializeField]
		private string _PrefabName;
		public string PrefabName => _PrefabName;

		[SerializeField]
		private string _ShowName;
		public string ShowName => _ShowName;

		[SerializeField]
		private int _MaxNum;
		public int MaxNum => _MaxNum;

		[SerializeField]
		private int _MinNum;
		public int MinNum => _MinNum;

		[SerializeField]
		private string _UIAdapter;
		public string UIAdapter => _UIAdapter;

		[SerializeField]
		private int _PlayerStateID;
		public int PlayerStateID => _PlayerStateID;

		[SerializeField]
		private int _touchType;
		public int touchType => _touchType;

		[SerializeField]
		private string _TouchIcon;
		public string TouchIcon => _TouchIcon;

		[SerializeField]
		private bool _Enable;
		public bool Enable => _Enable;

		[SerializeField]
		private int _LoadState;
		public int LoadState => _LoadState;


		public GamePropData()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _Id);
			EsParser.TryParse(cells[column++], out _Order);
			EsParser.TryParse(cells[column++], out _ModelType);
			EsParser.TryParse(cells[column++], out _BannerType);
			EsParser.TryParse(cells[column++], out _HandleType);
			EsParser.TryParse(cells[column++], out _IconName);
			EsParser.TryParse(cells[column++], out _PrefabName);
			EsParser.TryParse(cells[column++], out _ShowName);
			EsParser.TryParse(cells[column++], out _MaxNum);
			EsParser.TryParse(cells[column++], out _MinNum);
			EsParser.TryParse(cells[column++], out _UIAdapter);
			EsParser.TryParse(cells[column++], out _PlayerStateID);
			EsParser.TryParse(cells[column++], out _touchType);
			EsParser.TryParse(cells[column++], out _TouchIcon);
			EsParser.TryParse(cells[column++], out _Enable);
			EsParser.TryParse(cells[column++], out _LoadState);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}