//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class GashaponViewConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _ViewId;
		public int ViewId => _ViewId;

		[SerializeField]
		private string _CurrencyType;
		public string CurrencyType => _CurrencyType;

		[SerializeField]
		private string _GashaName;
		public string GashaName => _GashaName;

		[SerializeField]
		private string _GashaId;
		public string GashaId => _GashaId;

		[SerializeField]
		private string _BgColor;
		public string BgColor => _BgColor;

		[SerializeField]
		private string _GashaColor1;
		public string GashaColor1 => _GashaColor1;

		[SerializeField]
		private string _GashaColor2;
		public string GashaColor2 => _GashaColor2;

		[SerializeField]
		private List<string> _BgSpriteIds;
		public List<string> BgSpriteIds => _BgSpriteIds;

		[SerializeField]
		private string _AtlasPath;
		public string AtlasPath => _AtlasPath;

		[SerializeField]
		private int _CustomType;
		public int CustomType => _CustomType;

		[SerializeField]
		private string _BannerPrefab;
		public string BannerPrefab => _BannerPrefab;

		[SerializeField]
		private string _ViewPrefab;
		public string ViewPrefab => _ViewPrefab;

		[SerializeField]
		private string _RulePath;
		public string RulePath => _RulePath;

		[SerializeField]
		private string _BgPath;
		public string BgPath => _BgPath;


		public GashaponViewConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _ViewId);
			EsParser.TryParse(cells[column++], out _CurrencyType);
			EsParser.TryParse(cells[column++], out _GashaName);
			EsParser.TryParse(cells[column++], out _GashaId);
			EsParser.TryParse(cells[column++], out _BgColor);
			EsParser.TryParse(cells[column++], out _GashaColor1);
			EsParser.TryParse(cells[column++], out _GashaColor2);
			string[] _BgSpriteIds_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_BgSpriteIds = new List<string>(_BgSpriteIds_parts_.Length);
			for(int i = 0; i < _BgSpriteIds_parts_.Length; i++)
			{
				EsParser.TryParse(_BgSpriteIds_parts_[i], out string _temp_);
				_BgSpriteIds.Add(_temp_);
			}
			EsParser.TryParse(cells[column++], out _AtlasPath);
			EsParser.TryParse(cells[column++], out _CustomType);
			EsParser.TryParse(cells[column++], out _BannerPrefab);
			EsParser.TryParse(cells[column++], out _ViewPrefab);
			EsParser.TryParse(cells[column++], out _RulePath);
			EsParser.TryParse(cells[column++], out _BgPath);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}