//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class InstrumentToneConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _pgcId;
		public string pgcId => _pgcId;

		[SerializeField]
		private string _toneName;
		public string toneName => _toneName;

		[SerializeField]
		private int _toneType;
		public int toneType => _toneType;

		[SerializeField]
		private int _toneClassifyType;
		public int toneClassifyType => _toneClassifyType;

		[SerializeField]
		private int _longShortType;
		public int longShortType => _longShortType;

		[SerializeField]
		private List<string> _syllableList;
		public List<string> syllableList => _syllableList;

		[SerializeField]
		private int _isVip;
		public int isVip => _isVip;

		[SerializeField]
		private string _stopName;
		public string stopName => _stopName;


		public InstrumentToneConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _pgcId);
			EsParser.TryParse(cells[column++], out _toneName);
			EsParser.TryParse(cells[column++], out _toneType);
			EsParser.TryParse(cells[column++], out _toneClassifyType);
			EsParser.TryParse(cells[column++], out _longShortType);
			string[] _syllableList_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_syllableList = new List<string>(_syllableList_parts_.Length);
			for(int i = 0; i < _syllableList_parts_.Length; i++)
			{
				EsParser.TryParse(_syllableList_parts_[i], out string _temp_);
				_syllableList.Add(_temp_);
			}
			EsParser.TryParse(cells[column++], out _isVip);
			EsParser.TryParse(cells[column++], out _stopName);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}