//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class InstrumentConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _pgcId;
		public string pgcId => _pgcId;

		[SerializeField]
		private string _moveId;
		public string moveId => _moveId;

		[SerializeField]
		private string _toneId;
		public string toneId => _toneId;


		public InstrumentConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _pgcId);
			EsParser.TryParse(cells[column++], out _moveId);
			EsParser.TryParse(cells[column++], out _toneId);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}