//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class NetHttpBusiness : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _Id;
		public string Id => _Id;

		[SerializeField]
		private string _HttpUrl;
		public string HttpUrl => _HttpUrl;

		[SerializeField]
		private string _ParamStr;
		public string ParamStr => _ParamStr;

		[SerializeField]
		private int _IsPreRequest;
		public int IsPreRequest => _IsPreRequest;

		[SerializeField]
		private bool _IsCache;
		public bool IsCache => _IsCache;

		[SerializeField]
		private string _NextCmd;
		public string NextCmd => _NextCmd;

		[SerializeField]
		private int _OptType;
		public int OptType => _OptType;

		[SerializeField]
		private string _Arg0;
		public string Arg0 => _Arg0;

		[SerializeField]
		private string _Arg1;
		public string Arg1 => _Arg1;

		[SerializeField]
		private string _ConditionFilter;
		public string ConditionFilter => _ConditionFilter;


		public NetHttpBusiness()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _Id);
			EsParser.TryParse(cells[column++], out _HttpUrl);
			EsParser.TryParse(cells[column++], out _ParamStr);
			EsParser.TryParse(cells[column++], out _IsPreRequest);
			EsParser.TryParse(cells[column++], out _IsCache);
			EsParser.TryParse(cells[column++], out _NextCmd);
			EsParser.TryParse(cells[column++], out _OptType);
			EsParser.TryParse(cells[column++], out _Arg0);
			EsParser.TryParse(cells[column++], out _Arg1);
			EsParser.TryParse(cells[column++], out _ConditionFilter);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}