//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class NormalSkyboxData : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _Id;
		public string Id => _Id;

		[SerializeField]
		private string _Icon;
		public string Icon => _Icon;

		[SerializeField]
		private int _order;
		public int order => _order;

		[SerializeField]
		private List<string> _textures;
		public List<string> textures => _textures;

		[SerializeField]
		private string _cubemap;
		public string cubemap => _cubemap;

		[SerializeField]
		private int _skyType;
		public int skyType => _skyType;

		[SerializeField]
		private int _GradientType;
		public int GradientType => _GradientType;

		[SerializeField]
		private UnityEngine.Color _Sky;
		public UnityEngine.Color Sky => _Sky;

		[SerializeField]
		private UnityEngine.Color _Equator;
		public UnityEngine.Color Equator => _Equator;

		[SerializeField]
		private UnityEngine.Color _Ground;
		public UnityEngine.Color Ground => _Ground;

		[SerializeField]
		private UnityEngine.Color _Dirctional;
		public UnityEngine.Color Dirctional => _Dirctional;

		[SerializeField]
		private float _Intensity;
		public float Intensity => _Intensity;

		[SerializeField]
		private UnityEngine.Vector2 _Angle;
		public UnityEngine.Vector2 Angle => _Angle;

		[SerializeField]
		private float _ReflectionIntensity;
		public float ReflectionIntensity => _ReflectionIntensity;


		public NormalSkyboxData()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _Id);
			EsParser.TryParse(cells[column++], out _Icon);
			EsParser.TryParse(cells[column++], out _order);
			string[] _textures_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_textures = new List<string>(_textures_parts_.Length);
			for(int i = 0; i < _textures_parts_.Length; i++)
			{
				EsParser.TryParse(_textures_parts_[i], out string _temp_);
				_textures.Add(_temp_);
			}
			EsParser.TryParse(cells[column++], out _cubemap);
			EsParser.TryParse(cells[column++], out _skyType);
			EsParser.TryParse(cells[column++], out _GradientType);
			_Sky = new UnityEngine.Color();
			UnityTypesParse.Parse(ref _Sky, cells[column++]);
			_Equator = new UnityEngine.Color();
			UnityTypesParse.Parse(ref _Equator, cells[column++]);
			_Ground = new UnityEngine.Color();
			UnityTypesParse.Parse(ref _Ground, cells[column++]);
			_Dirctional = new UnityEngine.Color();
			UnityTypesParse.Parse(ref _Dirctional, cells[column++]);
			EsParser.TryParse(cells[column++], out _Intensity);
			_Angle = new UnityEngine.Vector2();
			UnityTypesParse.Parse(ref _Angle, cells[column++]);
			EsParser.TryParse(cells[column++], out _ReflectionIntensity);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}