//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	public sealed partial class NormalSkyboxDataTable : EsRowDataTable
	{
		[SerializeField]
		private List<NormalSkyboxData> _dataList = new List<NormalSkyboxData>();

		private Dictionary<string, NormalSkyboxData> _dataMap;
		public Dictionary<string, NormalSkyboxData> DataMap => _dataMap;
		public List<NormalSkyboxData> DataList => _dataList;

		public NormalSkyboxData Get(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
		public NormalSkyboxData this[string key] => _dataMap.TryGetValue(key, out var v) ? v : null;

		protected override void OnDeserialized()
		{
			_dataMap = new Dictionary<string, NormalSkyboxData>(_dataList.Count);
			foreach (var data in _dataList)
			{
				_dataMap.Add(data.Id, data);
				(data as ISerializationCallbackReceiver).OnAfterDeserialize();
			}
			PostInit();
		}

		partial void PostInit();
	}
}
