//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class OtherPublishPrice : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _Id;
		public int Id => _Id;

		[SerializeField]
		private List<int> _prices;
		public List<int> prices => _prices;

		[SerializeField]
		private List<int> _animePrices;
		public List<int> animePrices => _animePrices;

		[SerializeField]
		private int _normalLowPrice;
		public int normalLowPrice => _normalLowPrice;

		[SerializeField]
		private int _animeLowPrice;
		public int animeLowPrice => _animeLowPrice;

		[SerializeField]
		private List<int> _globalPrices;
		public List<int> globalPrices => _globalPrices;

		[SerializeField]
		private int _globalLowPrice;
		public int globalLowPrice => _globalLowPrice;


		public OtherPublishPrice()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _Id);
			string[] _prices_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_prices = new List<int>(_prices_parts_.Length);
			for(int i = 0; i < _prices_parts_.Length; i++)
			{
				EsParser.TryParse(_prices_parts_[i], out int _temp_);
				_prices.Add(_temp_);
			}
			string[] _animePrices_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_animePrices = new List<int>(_animePrices_parts_.Length);
			for(int i = 0; i < _animePrices_parts_.Length; i++)
			{
				EsParser.TryParse(_animePrices_parts_[i], out int _temp_);
				_animePrices.Add(_temp_);
			}
			EsParser.TryParse(cells[column++], out _normalLowPrice);
			EsParser.TryParse(cells[column++], out _animeLowPrice);
			string[] _globalPrices_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_globalPrices = new List<int>(_globalPrices_parts_.Length);
			for(int i = 0; i < _globalPrices_parts_.Length; i++)
			{
				EsParser.TryParse(_globalPrices_parts_[i], out int _temp_);
				_globalPrices.Add(_temp_);
			}
			EsParser.TryParse(cells[column++], out _globalLowPrice);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}