//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class PetUGCClothEditorConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _PartName;
		public string PartName => _PartName;

		[SerializeField]
		private float _ZoomSpeed;
		public float ZoomSpeed => _ZoomSpeed;

		[SerializeField]
		private float _ZoomScaleMin;
		public float ZoomScaleMin => _ZoomScaleMin;

		[SerializeField]
		private float _ZoomScaleMax;
		public float ZoomScaleMax => _ZoomScaleMax;

		[SerializeField]
		private float _YRotateSpeed;
		public float YRotateSpeed => _YRotateSpeed;

		[SerializeField]
		private float _UpDownMoveSpeed;
		public float UpDownMoveSpeed => _UpDownMoveSpeed;

		[SerializeField]
		private float _UpDownMoveMin;
		public float UpDownMoveMin => _UpDownMoveMin;

		[SerializeField]
		private float _UpDownMoveMax;
		public float UpDownMoveMax => _UpDownMoveMax;

		[SerializeField]
		private UnityEngine.Vector3 _DefalutModelPos;
		public UnityEngine.Vector3 DefalutModelPos => _DefalutModelPos;

		[SerializeField]
		private UnityEngine.Vector3 _DefalutChildPos;
		public UnityEngine.Vector3 DefalutChildPos => _DefalutChildPos;

		[SerializeField]
		private UnityEngine.Vector3 _DefalutModelRot;
		public UnityEngine.Vector3 DefalutModelRot => _DefalutModelRot;

		[SerializeField]
		private UnityEngine.Vector3 _DefalutModelScale;
		public UnityEngine.Vector3 DefalutModelScale => _DefalutModelScale;

		[SerializeField]
		private UnityEngine.Vector3 _ShotCameraPos;
		public UnityEngine.Vector3 ShotCameraPos => _ShotCameraPos;

		[SerializeField]
		private UnityEngine.Vector3 _ShotCameraRot;
		public UnityEngine.Vector3 ShotCameraRot => _ShotCameraRot;


		public PetUGCClothEditorConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _PartName);
			EsParser.TryParse(cells[column++], out _ZoomSpeed);
			EsParser.TryParse(cells[column++], out _ZoomScaleMin);
			EsParser.TryParse(cells[column++], out _ZoomScaleMax);
			EsParser.TryParse(cells[column++], out _YRotateSpeed);
			EsParser.TryParse(cells[column++], out _UpDownMoveSpeed);
			EsParser.TryParse(cells[column++], out _UpDownMoveMin);
			EsParser.TryParse(cells[column++], out _UpDownMoveMax);
			_DefalutModelPos = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _DefalutModelPos, cells[column++]);
			_DefalutChildPos = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _DefalutChildPos, cells[column++]);
			_DefalutModelRot = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _DefalutModelRot, cells[column++]);
			_DefalutModelScale = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _DefalutModelScale, cells[column++]);
			_ShotCameraPos = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _ShotCameraPos, cells[column++]);
			_ShotCameraRot = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _ShotCameraRot, cells[column++]);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}