//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class PgcVehicleConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _id;
		public int id => _id;

		[SerializeField]
		private string _type;
		public string type => _type;

		[SerializeField]
		private string _controlType;
		public string controlType => _controlType;

		[SerializeField]
		private string _loadPath;
		public string loadPath => _loadPath;

		[SerializeField]
		private List<UnityEngine.Vector3> _seatOffset;
		public List<UnityEngine.Vector3> seatOffset => _seatOffset;

		[SerializeField]
		private SpecialAnimInfo _idleAnim;
		public SpecialAnimInfo idleAnim => _idleAnim;

		[SerializeField]
		private SpecialAnimInfo _runAnim;
		public SpecialAnimInfo runAnim => _runAnim;

		[SerializeField]
		private SpecialAnimInfo _jumpAnim;
		public SpecialAnimInfo jumpAnim => _jumpAnim;

		[SerializeField]
		private SpecialAnimInfo _fallAnim;
		public SpecialAnimInfo fallAnim => _fallAnim;

		[SerializeField]
		private SpecialAnimInfo _landAnim;
		public SpecialAnimInfo landAnim => _landAnim;

		[SerializeField]
		private float _moveVelocity;
		public float moveVelocity => _moveVelocity;

		[SerializeField]
		private float _angleVelocity;
		public float angleVelocity => _angleVelocity;

		[SerializeField]
		private float _jumpVelocity;
		public float jumpVelocity => _jumpVelocity;

		[SerializeField]
		private float _fallVelocity;
		public float fallVelocity => _fallVelocity;

		[SerializeField]
		private int _maxJumpTime;
		public int maxJumpTime => _maxJumpTime;

		[SerializeField]
		private float _jumpCoolDown;
		public float jumpCoolDown => _jumpCoolDown;

		[SerializeField]
		private float _skill1Value;
		public float skill1Value => _skill1Value;

		[SerializeField]
		private float _skill1CoolDown;
		public float skill1CoolDown => _skill1CoolDown;

		[SerializeField]
		private float _skill2Value;
		public float skill2Value => _skill2Value;

		[SerializeField]
		private float _skill2CoolDown;
		public float skill2CoolDown => _skill2CoolDown;

		[SerializeField]
		private string _KVC;
		public string KVC => _KVC;

		[SerializeField]
		private SpecialAnimInfo _vStartAnim;
		public SpecialAnimInfo vStartAnim => _vStartAnim;

		[SerializeField]
		private SpecialAnimInfo _vIdleAnim;
		public SpecialAnimInfo vIdleAnim => _vIdleAnim;

		[SerializeField]
		private SpecialAnimInfo _vRunAnim;
		public SpecialAnimInfo vRunAnim => _vRunAnim;

		[SerializeField]
		private SpecialAnimInfo _vJumpAnim;
		public SpecialAnimInfo vJumpAnim => _vJumpAnim;

		[SerializeField]
		private SpecialAnimInfo _vFallAnim;
		public SpecialAnimInfo vFallAnim => _vFallAnim;

		[SerializeField]
		private SpecialAnimInfo _vLandAnim;
		public SpecialAnimInfo vLandAnim => _vLandAnim;

		[SerializeField]
		private SpecialAnimInfo _vSkill1StartAnim;
		public SpecialAnimInfo vSkill1StartAnim => _vSkill1StartAnim;

		[SerializeField]
		private SpecialAnimInfo _vSkill1LoopAnim;
		public SpecialAnimInfo vSkill1LoopAnim => _vSkill1LoopAnim;

		[SerializeField]
		private SpecialAnimInfo _vSkill1EndAnim;
		public SpecialAnimInfo vSkill1EndAnim => _vSkill1EndAnim;

		[SerializeField]
		private SpecialAnimInfo _vSkill2StartAnim;
		public SpecialAnimInfo vSkill2StartAnim => _vSkill2StartAnim;

		[SerializeField]
		private SpecialAnimInfo _vSkill2LoopAnim;
		public SpecialAnimInfo vSkill2LoopAnim => _vSkill2LoopAnim;

		[SerializeField]
		private SpecialAnimInfo _vSkill2EndAnim;
		public SpecialAnimInfo vSkill2EndAnim => _vSkill2EndAnim;

		[SerializeField]
		private string _inputPrefab;
		public string inputPrefab => _inputPrefab;

		[SerializeField]
		private string _honkingAudio;
		public string honkingAudio => _honkingAudio;

		[SerializeField]
		private SpecialAnimCameraInfo _fittingRoomConfig;
		public SpecialAnimCameraInfo fittingRoomConfig => _fittingRoomConfig;

		[SerializeField]
		private UnityEngine.Vector3 _fittingRoomPosConfig;
		public UnityEngine.Vector3 fittingRoomPosConfig => _fittingRoomPosConfig;

		[SerializeField]
		private UnityEngine.Vector3 _gameCameraOffset;
		public UnityEngine.Vector3 gameCameraOffset => _gameCameraOffset;

		[SerializeField]
		private UnityEngine.Vector3 _hallAvatarOffset;
		public UnityEngine.Vector3 hallAvatarOffset => _hallAvatarOffset;


		public PgcVehicleConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _id);
			EsParser.TryParse(cells[column++], out _type);
			EsParser.TryParse(cells[column++], out _controlType);
			EsParser.TryParse(cells[column++], out _loadPath);
			string[] _seatOffset_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_seatOffset = new List<UnityEngine.Vector3>(_seatOffset_parts_.Length);
			for(int i = 0; i < _seatOffset_parts_.Length; i++)
			{
				var _temp_ = new UnityEngine.Vector3();
				UnityTypesParse.Parse(ref _temp_, _seatOffset_parts_[i]);
				_seatOffset.Add(_temp_);
			}
			_idleAnim = new SpecialAnimInfo();
			_idleAnim.Parse(cells[column++]);
			_runAnim = new SpecialAnimInfo();
			_runAnim.Parse(cells[column++]);
			_jumpAnim = new SpecialAnimInfo();
			_jumpAnim.Parse(cells[column++]);
			_fallAnim = new SpecialAnimInfo();
			_fallAnim.Parse(cells[column++]);
			_landAnim = new SpecialAnimInfo();
			_landAnim.Parse(cells[column++]);
			EsParser.TryParse(cells[column++], out _moveVelocity);
			EsParser.TryParse(cells[column++], out _angleVelocity);
			EsParser.TryParse(cells[column++], out _jumpVelocity);
			EsParser.TryParse(cells[column++], out _fallVelocity);
			EsParser.TryParse(cells[column++], out _maxJumpTime);
			EsParser.TryParse(cells[column++], out _jumpCoolDown);
			EsParser.TryParse(cells[column++], out _skill1Value);
			EsParser.TryParse(cells[column++], out _skill1CoolDown);
			EsParser.TryParse(cells[column++], out _skill2Value);
			EsParser.TryParse(cells[column++], out _skill2CoolDown);
			EsParser.TryParse(cells[column++], out _KVC);
			_vStartAnim = new SpecialAnimInfo();
			_vStartAnim.Parse(cells[column++]);
			_vIdleAnim = new SpecialAnimInfo();
			_vIdleAnim.Parse(cells[column++]);
			_vRunAnim = new SpecialAnimInfo();
			_vRunAnim.Parse(cells[column++]);
			_vJumpAnim = new SpecialAnimInfo();
			_vJumpAnim.Parse(cells[column++]);
			_vFallAnim = new SpecialAnimInfo();
			_vFallAnim.Parse(cells[column++]);
			_vLandAnim = new SpecialAnimInfo();
			_vLandAnim.Parse(cells[column++]);
			_vSkill1StartAnim = new SpecialAnimInfo();
			_vSkill1StartAnim.Parse(cells[column++]);
			_vSkill1LoopAnim = new SpecialAnimInfo();
			_vSkill1LoopAnim.Parse(cells[column++]);
			_vSkill1EndAnim = new SpecialAnimInfo();
			_vSkill1EndAnim.Parse(cells[column++]);
			_vSkill2StartAnim = new SpecialAnimInfo();
			_vSkill2StartAnim.Parse(cells[column++]);
			_vSkill2LoopAnim = new SpecialAnimInfo();
			_vSkill2LoopAnim.Parse(cells[column++]);
			_vSkill2EndAnim = new SpecialAnimInfo();
			_vSkill2EndAnim.Parse(cells[column++]);
			EsParser.TryParse(cells[column++], out _inputPrefab);
			EsParser.TryParse(cells[column++], out _honkingAudio);
			_fittingRoomConfig = new SpecialAnimCameraInfo();
			_fittingRoomConfig.Parse(cells[column++]);
			_fittingRoomPosConfig = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _fittingRoomPosConfig, cells[column++]);
			_gameCameraOffset = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _gameCameraOffset, cells[column++]);
			_hallAvatarOffset = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _hallAvatarOffset, cells[column++]);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}