//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class PoseEditOperation : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _JointName;
		public string JointName => _JointName;

		[SerializeField]
		private int _RoleType;
		public int RoleType => _RoleType;

		[SerializeField]
		private int _PartType;
		public int PartType => _PartType;

		[SerializeField]
		private int _Move;
		public int Move => _Move;

		[SerializeField]
		private int _Rotate;
		public int Rotate => _Rotate;

		[SerializeField]
		private int _Scale;
		public int Scale => _Scale;

		[SerializeField]
		private int _Bind;
		public int Bind => _Bind;

		[SerializeField]
		private int _Change;
		public int Change => _Change;

		[SerializeField]
		private int _Remove;
		public int Remove => _Remove;

		[SerializeField]
		private int _Delete;
		public int Delete => _Delete;

		[SerializeField]
		private bool _IsLimit;
		public bool IsLimit => _IsLimit;

		[SerializeField]
		private UnityEngine.Vector3 _MoveMin;
		public UnityEngine.Vector3 MoveMin => _MoveMin;

		[SerializeField]
		private UnityEngine.Vector3 _MoveMax;
		public UnityEngine.Vector3 MoveMax => _MoveMax;

		[SerializeField]
		private bool _IsSpecialScale;
		public bool IsSpecialScale => _IsSpecialScale;


		public PoseEditOperation()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _JointName);
			EsParser.TryParse(cells[column++], out _RoleType);
			EsParser.TryParse(cells[column++], out _PartType);
			EsParser.TryParse(cells[column++], out _Move);
			EsParser.TryParse(cells[column++], out _Rotate);
			EsParser.TryParse(cells[column++], out _Scale);
			EsParser.TryParse(cells[column++], out _Bind);
			EsParser.TryParse(cells[column++], out _Change);
			EsParser.TryParse(cells[column++], out _Remove);
			EsParser.TryParse(cells[column++], out _Delete);
			EsParser.TryParse(cells[column++], out _IsLimit);
			_MoveMin = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _MoveMin, cells[column++]);
			_MoveMax = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _MoveMax, cells[column++]);
			EsParser.TryParse(cells[column++], out _IsSpecialScale);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}