//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class PoseModeConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _Id;
		public int Id => _Id;

		[SerializeField]
		private List<string> _JointNames;
		public List<string> JointNames => _JointNames;

		[SerializeField]
		private List<UnityEngine.Vector3> _EditPos;
		public List<UnityEngine.Vector3> EditPos => _EditPos;

		[SerializeField]
		private List<float> _roleHeight;
		public List<float> roleHeight => _roleHeight;

		[SerializeField]
		private List<UnityEngine.Vector3> _RoleDefPos;
		public List<UnityEngine.Vector3> RoleDefPos => _RoleDefPos;

		[SerializeField]
		private UnityEngine.Vector3 _EditCamPos;
		public UnityEngine.Vector3 EditCamPos => _EditCamPos;

		[SerializeField]
		private UnityEngine.Vector3 _EditCamRot;
		public UnityEngine.Vector3 EditCamRot => _EditCamRot;

		[SerializeField]
		private UnityEngine.Vector3 _UIParentPos;
		public UnityEngine.Vector3 UIParentPos => _UIParentPos;

		[SerializeField]
		private float _ShotCamSize;
		public float ShotCamSize => _ShotCamSize;

		[SerializeField]
		private UnityEngine.Vector3 _ShotCamPos;
		public UnityEngine.Vector3 ShotCamPos => _ShotCamPos;

		[SerializeField]
		private List<UnityEngine.Vector3> _ShotEditPos;
		public List<UnityEngine.Vector3> ShotEditPos => _ShotEditPos;

		[SerializeField]
		private List<string> _BindNames;
		public List<string> BindNames => _BindNames;

		[SerializeField]
		private List<int> _BindIndexs;
		public List<int> BindIndexs => _BindIndexs;


		public PoseModeConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _Id);
			string[] _JointNames_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_JointNames = new List<string>(_JointNames_parts_.Length);
			for(int i = 0; i < _JointNames_parts_.Length; i++)
			{
				EsParser.TryParse(_JointNames_parts_[i], out string _temp_);
				_JointNames.Add(_temp_);
			}
			string[] _EditPos_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_EditPos = new List<UnityEngine.Vector3>(_EditPos_parts_.Length);
			for(int i = 0; i < _EditPos_parts_.Length; i++)
			{
				var _temp_ = new UnityEngine.Vector3();
				UnityTypesParse.Parse(ref _temp_, _EditPos_parts_[i]);
				_EditPos.Add(_temp_);
			}
			string[] _roleHeight_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_roleHeight = new List<float>(_roleHeight_parts_.Length);
			for(int i = 0; i < _roleHeight_parts_.Length; i++)
			{
				EsParser.TryParse(_roleHeight_parts_[i], out float _temp_);
				_roleHeight.Add(_temp_);
			}
			string[] _RoleDefPos_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_RoleDefPos = new List<UnityEngine.Vector3>(_RoleDefPos_parts_.Length);
			for(int i = 0; i < _RoleDefPos_parts_.Length; i++)
			{
				var _temp_ = new UnityEngine.Vector3();
				UnityTypesParse.Parse(ref _temp_, _RoleDefPos_parts_[i]);
				_RoleDefPos.Add(_temp_);
			}
			_EditCamPos = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _EditCamPos, cells[column++]);
			_EditCamRot = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _EditCamRot, cells[column++]);
			_UIParentPos = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _UIParentPos, cells[column++]);
			EsParser.TryParse(cells[column++], out _ShotCamSize);
			_ShotCamPos = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _ShotCamPos, cells[column++]);
			string[] _ShotEditPos_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_ShotEditPos = new List<UnityEngine.Vector3>(_ShotEditPos_parts_.Length);
			for(int i = 0; i < _ShotEditPos_parts_.Length; i++)
			{
				var _temp_ = new UnityEngine.Vector3();
				UnityTypesParse.Parse(ref _temp_, _ShotEditPos_parts_[i]);
				_ShotEditPos.Add(_temp_);
			}
			string[] _BindNames_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_BindNames = new List<string>(_BindNames_parts_.Length);
			for(int i = 0; i < _BindNames_parts_.Length; i++)
			{
				EsParser.TryParse(_BindNames_parts_[i], out string _temp_);
				_BindNames.Add(_temp_);
			}
			string[] _BindIndexs_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_BindIndexs = new List<int>(_BindIndexs_parts_.Length);
			for(int i = 0; i < _BindIndexs_parts_.Length; i++)
			{
				EsParser.TryParse(_BindIndexs_parts_[i], out int _temp_);
				_BindIndexs.Add(_temp_);
			}
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}