//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class PreviewParamsConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _Id;
		public int Id => _Id;

		[SerializeField]
		private UnityEngine.Vector3 _ModelLocalPos;
		public UnityEngine.Vector3 ModelLocalPos => _ModelLocalPos;

		[SerializeField]
		private UnityEngine.Vector3 _ModelLocalEulerAngles;
		public UnityEngine.Vector3 ModelLocalEulerAngles => _ModelLocalEulerAngles;

		[SerializeField]
		private UnityEngine.Vector3 _ModelLocalScale;
		public UnityEngine.Vector3 ModelLocalScale => _ModelLocalScale;

		[SerializeField]
		private UnityEngine.Vector3 _CameraLocalPos;
		public UnityEngine.Vector3 CameraLocalPos => _CameraLocalPos;

		[SerializeField]
		private UnityEngine.Vector3 _CameraLocalEulerAngles;
		public UnityEngine.Vector3 CameraLocalEulerAngles => _CameraLocalEulerAngles;

		[SerializeField]
		private float _CameraFov;
		public float CameraFov => _CameraFov;


		public PreviewParamsConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _Id);
			_ModelLocalPos = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _ModelLocalPos, cells[column++]);
			_ModelLocalEulerAngles = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _ModelLocalEulerAngles, cells[column++]);
			_ModelLocalScale = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _ModelLocalScale, cells[column++]);
			_CameraLocalPos = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _CameraLocalPos, cells[column++]);
			_CameraLocalEulerAngles = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _CameraLocalEulerAngles, cells[column++]);
			EsParser.TryParse(cells[column++], out _CameraFov);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}