//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	public sealed partial class PropTemplateTable : EsRowDataTable
	{
		[SerializeField]
		private List<PropTemplate> _dataList = new List<PropTemplate>();

		private Dictionary<string, PropTemplate> _dataMap;
		public Dictionary<string, PropTemplate> DataMap => _dataMap;
		public List<PropTemplate> DataList => _dataList;

		public PropTemplate Get(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
		public PropTemplate this[string key] => _dataMap.TryGetValue(key, out var v) ? v : null;

		protected override void OnDeserialized()
		{
			_dataMap = new Dictionary<string, PropTemplate>(_dataList.Count);
			foreach (var data in _dataList)
			{
				_dataMap.Add(data.Id, data);
				(data as ISerializationCallbackReceiver).OnAfterDeserialize();
			}
			PostInit();
		}

		partial void PostInit();
	}
}
