//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class PropTemplate : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _Id;
		public string Id => _Id;

		[SerializeField]
		private string _Name;
		public string Name => _Name;

		[SerializeField]
		private string _Cover;
		public string Cover => _Cover;

		[SerializeField]
		private string _MetaDataUrl;
		public string MetaDataUrl => _MetaDataUrl;

		[SerializeField]
		private string _RemoteCover;
		public string RemoteCover => _RemoteCover;


		public PropTemplate()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _Id);
			EsParser.TryParse(cells[column++], out _Name);
			EsParser.TryParse(cells[column++], out _Cover);
			EsParser.TryParse(cells[column++], out _MetaDataUrl);
			EsParser.TryParse(cells[column++], out _RemoteCover);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}