//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class RechargeViewConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _ViewId;
		public int ViewId => _ViewId;

		[SerializeField]
		private string _ViewName;
		public string ViewName => _ViewName;

		[SerializeField]
		private string _ViewPrefab;
		public string ViewPrefab => _ViewPrefab;


		public RechargeViewConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _ViewId);
			EsParser.TryParse(cells[column++], out _ViewName);
			EsParser.TryParse(cells[column++], out _ViewPrefab);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}