//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class RedDotBindConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _type;
		public int type => _type;

		[SerializeField]
		private List<int> _bindRedDotUI;
		public List<int> bindRedDotUI => _bindRedDotUI;


		public RedDotBindConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _type);
			string[] _bindRedDotUI_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_bindRedDotUI = new List<int>(_bindRedDotUI_parts_.Length);
			for(int i = 0; i < _bindRedDotUI_parts_.Length; i++)
			{
				EsParser.TryParse(_bindRedDotUI_parts_[i], out int _temp_);
				_bindRedDotUI.Add(_temp_);
			}
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}