//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class RewardLevelConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _LevelType;
		public int LevelType => _LevelType;

		[SerializeField]
		private string _UnselectSpriteName;
		public string UnselectSpriteName => _UnselectSpriteName;

		[SerializeField]
		private string _SelectSpriteName;
		public string SelectSpriteName => _SelectSpriteName;

		[SerializeField]
		private string _BgMarkImg;
		public string BgMarkImg => _BgMarkImg;

		[SerializeField]
		private string _ColorStr;
		public string ColorStr => _ColorStr;


		public RewardLevelConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _LevelType);
			EsParser.TryParse(cells[column++], out _UnselectSpriteName);
			EsParser.TryParse(cells[column++], out _SelectSpriteName);
			EsParser.TryParse(cells[column++], out _BgMarkImg);
			EsParser.TryParse(cells[column++], out _ColorStr);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}