//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	public sealed partial class SpecialSkinConfigTable : EsRowDataTable
	{
		[SerializeField]
		private List<SpecialSkinConfig> _dataList = new List<SpecialSkinConfig>();

		private Dictionary<string, SpecialSkinConfig> _dataMap;
		public Dictionary<string, SpecialSkinConfig> DataMap => _dataMap;
		public List<SpecialSkinConfig> DataList => _dataList;

		public SpecialSkinConfig Get(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
		public SpecialSkinConfig this[string key] => _dataMap.TryGetValue(key, out var v) ? v : null;

		protected override void OnDeserialized()
		{
			_dataMap = new Dictionary<string, SpecialSkinConfig>(_dataList.Count);
			foreach (var data in _dataList)
			{
				_dataMap.Add(data.Id, data);
				(data as ISerializationCallbackReceiver).OnAfterDeserialize();
			}
			PostInit();
		}

		partial void PostInit();
	}
}
