//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	public sealed partial class TaskConfigTable : EsRowDataTable
	{
		[SerializeField]
		private List<TaskConfig> _dataList = new List<TaskConfig>();

		private Dictionary<int, TaskConfig> _dataMap;
		public Dictionary<int, TaskConfig> DataMap => _dataMap;
		public List<TaskConfig> DataList => _dataList;

		public TaskConfig Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
		public TaskConfig this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

		protected override void OnDeserialized()
		{
			_dataMap = new Dictionary<int, TaskConfig>(_dataList.Count);
			foreach (var data in _dataList)
			{
				_dataMap.Add(data.id, data);
				(data as ISerializationCallbackReceiver).OnAfterDeserialize();
			}
			PostInit();
		}

		partial void PostInit();
	}
}
