//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class UgcAnimBgmConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _pgcId;
		public string pgcId => _pgcId;

		[SerializeField]
		private string _toneName;
		public string toneName => _toneName;

		[SerializeField]
		private string _eventName;
		public string eventName => _eventName;

		[SerializeField]
		private int _bgmLength;
		public int bgmLength => _bgmLength;

		[SerializeField]
		private int _isVip;
		public int isVip => _isVip;


		public UgcAnimBgmConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _pgcId);
			EsParser.TryParse(cells[column++], out _toneName);
			EsParser.TryParse(cells[column++], out _eventName);
			EsParser.TryParse(cells[column++], out _bgmLength);
			EsParser.TryParse(cells[column++], out _isVip);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}