//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class UIAvatarNullData : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private string _Id;
		public string Id => _Id;

		[SerializeField]
		private int _ResType;
		public int ResType => _ResType;

		[SerializeField]
		private string _Name;
		public string Name => _Name;

		[SerializeField]
		private int _isNull;
		public int isNull => _isNull;


		public UIAvatarNullData()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _Id);
			EsParser.TryParse(cells[column++], out _ResType);
			EsParser.TryParse(cells[column++], out _Name);
			EsParser.TryParse(cells[column++], out _isNull);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}