//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class UIPanel : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _PanelId;
		public int PanelId => _PanelId;

		[SerializeField]
		private int _WindowId;
		public int WindowId => _WindowId;

		[SerializeField]
		private string _Name;
		public string Name => _Name;

		[SerializeField]
		private string _ResPath;
		public string ResPath => _ResPath;

		[SerializeField]
		private int _Order;
		public int Order => _Order;

		[SerializeField]
		private int _FullScreen;
		public int FullScreen => _FullScreen;

		[SerializeField]
		private bool _IsAllowMultiInstance;
		public bool IsAllowMultiInstance => _IsAllowMultiInstance;

		[SerializeField]
		private bool _IsDestroyOnClose;
		public bool IsDestroyOnClose => _IsDestroyOnClose;


		public UIPanel()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _PanelId);
			EsParser.TryParse(cells[column++], out _WindowId);
			EsParser.TryParse(cells[column++], out _Name);
			EsParser.TryParse(cells[column++], out _ResPath);
			EsParser.TryParse(cells[column++], out _Order);
			EsParser.TryParse(cells[column++], out _FullScreen);
			EsParser.TryParse(cells[column++], out _IsAllowMultiInstance);
			EsParser.TryParse(cells[column++], out _IsDestroyOnClose);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}