//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class UnityTypes : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _Id;
		public int Id => _Id;

		[SerializeField]
		private UnityEngine.Vector2 _vec2;
		public UnityEngine.Vector2 vec2 => _vec2;

		[SerializeField]
		private UnityEngine.Vector3 _vec3;
		public UnityEngine.Vector3 vec3 => _vec3;

		[SerializeField]
		private List<UnityEngine.Vector3> _vec3s;
		public List<UnityEngine.Vector3> vec3s => _vec3s;

		[SerializeField]
		private List<int> _vec3DictKeys;
		[SerializeField]
		private List<UnityEngine.Vector3> _vec3DictValues;
		private Dictionary<int,UnityEngine.Vector3> _vec3Dict;
		public Dictionary<int,UnityEngine.Vector3> vec3Dict => _vec3Dict;


		public UnityTypes()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _Id);
			_vec2 = new UnityEngine.Vector2();
			UnityTypesParse.Parse(ref _vec2, cells[column++]);
			_vec3 = new UnityEngine.Vector3();
			UnityTypesParse.Parse(ref _vec3, cells[column++]);
			string[] _vec3s_parts_ = string.IsNullOrEmpty(cells[column]) ? 
			new string[0] : cells[column].Split(';');
			column++;
			_vec3s = new List<UnityEngine.Vector3>(_vec3s_parts_.Length);
			for(int i = 0; i < _vec3s_parts_.Length; i++)
			{
				var _temp_ = new UnityEngine.Vector3();
				UnityTypesParse.Parse(ref _temp_, _vec3s_parts_[i]);
				_vec3s.Add(_temp_);
			}
			string _vec3DictRawData = cells[column++];
			string[] _vec3DictPairs = _vec3DictRawData.Split(';');
			_vec3DictKeys = new List<int>();
			_vec3DictValues = new List<UnityEngine.Vector3>();
			for (int i = 0; i < _vec3DictPairs.Length; ++i)
			{
				string _vec3DictPair = _vec3DictPairs[i];
				string[] _vec3DictPairs2 = _vec3DictPair.Split(':');
				if (_vec3DictPairs2.Length < 2) continue;
				EsParser.TryParse(_vec3DictPairs2[0], out int _vec3DictK);
				var _temp_ = new UnityEngine.Vector3();
				UnityTypesParse.Parse(ref _temp_, _vec3DictPairs2[1]);
				_vec3DictKeys.Add(_vec3DictK);
				_vec3DictValues.Add(_temp_);
			}
		}
#endif
		protected override void OnDeserialized()
		{
			_vec3Dict = new Dictionary<int, UnityEngine.Vector3>(_vec3DictKeys.Count);
			for (int i = 0; i < _vec3DictKeys.Count; ++i)
			{
				var k = _vec3DictKeys[i];
				var v = _vec3DictValues[i];
				if (_vec3Dict.ContainsKey(k))
					EsLog.Error("Dictionary _vec3Dict already contains key " + k + ".");
				else
					_vec3Dict.Add(k, v);
			}

			PostInit();
		}

		partial void PostInit();
	}

}