//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace Es
{
	[Serializable]
	public sealed partial class WaterCubeConfig : EsRowData
	{
		[EsKeyField]
		[SerializeField]
		private int _Id;
		public int Id => _Id;

		[SerializeField]
		private UnityEngine.Color _surfaceColor;
		public UnityEngine.Color surfaceColor => _surfaceColor;

		[SerializeField]
		private float _opacity;
		public float opacity => _opacity;

		[SerializeField]
		private UnityEngine.Color _innerColor;
		public UnityEngine.Color innerColor => _innerColor;

		[SerializeField]
		private string _IconName;
		public string IconName => _IconName;


		public WaterCubeConfig()
		{
		}

#if UNITY_EDITOR
		private void Parse(List<string> cells, int column)
		{
			EsParser.TryParse(cells[column++], out _Id);
			_surfaceColor = new UnityEngine.Color();
			UnityTypesParse.Parse(ref _surfaceColor, cells[column++]);
			EsParser.TryParse(cells[column++], out _opacity);
			_innerColor = new UnityEngine.Color();
			UnityTypesParse.Parse(ref _innerColor, cells[column++]);
			EsParser.TryParse(cells[column++], out _IconName);
		}
#endif
		protected override void OnDeserialized()
		{

			PostInit();
		}

		partial void PostInit();
	}

}