/// <summary>
/// This script is generated by tools
/// 工具生成脚本，请勿手动编辑！！
/// </summary>
public enum AnimId
{
    Star = 0,
    SkiIn = 1,
    SkiOut = 2,
    SelfieIn = 3,
    SelfieOut = 4,
    Pose1 = 5,
    Pose2 = 6,
    Pose3 = 7,
    Pose4 = 8,
    Pose5 = 9,
    Pose6 = 10,
    SelfieIn_R = 11,
    SelfieOut_R = 12,
}
